/**
 * pyUnicode — the Unicode database of the bot's interpreter (CPython 3.11, unicodedata 14.0.0),
 * for every port of a Python builtin whose result depends on it: int() / float() of non-ASCII
 * digits and spaces, re `\d`, str.isspace() / str.strip(), str.isprintable() / repr().
 *
 * Node ships its own, newer Unicode (Node 22: 16.0), and CPython 3.12 ships 15.0.0 — neither
 * is the bot's. Characters assigned after 14.0.0 are unassigned (Cn) for the bot: not printable
 * (repr() escapes them) and never a digit (Kawi U+11F50 and Nag Mundari U+1E4F0 digits, new in
 * 15.0, make int() raise). The tables are generated by tests/challenge/gen/gen_unicode_tables.py
 * with the production interpreter; paste its output between the markers below.
 */

'use strict';

// BEGIN unicode tables
// unicodedata 14.0.0 (CPython 3.11.17)
const ND_ZEROS = [0x30, 0x660, 0x6f0, 0x7c0, 0x966, 0x9e6, 0xa66, 0xae6, 0xb66, 0xbe6, 0xc66, 0xce6, 0xd66, 0xde6, 0xe50, 0xed0, 0xf20, 0x1040, 0x1090, 0x17e0, 0x1810, 0x1946, 0x19d0, 0x1a80, 0x1a90, 0x1b50, 0x1bb0, 0x1c40, 0x1c50, 0xa620, 0xa8d0, 0xa900, 0xa9d0, 0xa9f0, 0xaa50, 0xabf0, 0xff10, 0x104a0, 0x10d30, 0x11066, 0x110f0, 0x11136, 0x111d0, 0x112f0, 0x11450, 0x114d0, 0x11650, 0x116c0, 0x11730, 0x118e0, 0x11950, 0x11c50, 0x11d50, 0x11da0, 0x16a60, 0x16ac0, 0x16b50, 0x1d7ce, 0x1d7d8, 0x1d7e2, 0x1d7ec, 0x1d7f6, 0x1e140, 0x1e2f0, 0x1e950, 0x1fbf0];
const PY_SPACE_HI = [0x85, 0xa0, 0x1680, 0x2000, 0x2001, 0x2002, 0x2003, 0x2004, 0x2005, 0x2006, 0x2007, 0x2008, 0x2009, 0x200a, 0x2028, 0x2029, 0x202f, 0x205f, 0x3000];
const NONPRINT = '3k.w,d.0,jv.1,7.3,8.0,2.0,l.0,b2.0,13.1,1f.1,4.0,1k.7,s.3,7.g,n.0,5d.0,1d.1,1o.1,2u.d,1o.1,1e.1,g.0,t.1,2.0,c.4,w.8,23.0,4i.0,9.1,3.1,n.0,8.0,2.2,5.1,a.1,3.1,5.7,2.3,3.0,6.1,q.1,4.0,7.3,3.1,n.0,8.0,3.0,3.0,3.1,2.0,6.3,3.1,4.2,2.6,5.0,2.6,i.9,4.0,a.0,4.0,n.0,8.0,3.0,6.1,b.0,4.0,4.1,2.e,5.1,d.6,8.0,4.0,9.1,3.1,n.0,8.0,3.0,6.1,a.1,3.1,4.6,4.3,3.0,6.1,j.9,3.0,7.2,4.0,5.2,3.0,2.0,3.2,3.2,4.2,d.3,6.2,4.0,5.1,2.5,2.d,m.4,e.0,4.0,o.0,h.1,a.0,4.0,5.6,3.0,4.1,2.1,5.1,b.6,n.0,4.0,o.0,b.0,6.1,a.0,4.0,5.6,3.5,3.0,5.1,b.0,3.c,e.0,4.0,1g.0,4.0,7.3,h.1,r.0,4.0,j.2,p.0,a.0,2.1,8.2,2.3,7.0,2.0,9.5,b.1,4.b,1n.3,u.10,3.0,2.0,6.0,p.0,2.0,o.1,6.0,2.0,7.1,b.1,5.v,21.0,11.3,14.0,11.0,g.0,e.10,5j.0,2.4,2.1,ai.0,5.1,8.0,2.0,5.1,16.0,5.1,y.0,5.1,8.0,2.0,5.1,g.0,1m.0,5.1,1w.1,x.2,r.5,2f.1,7.1,ht.0,t.2,2i.6,n.8,p.8,l.b,e.0,4.0,3.b,2n.1,b.5,b.5,f.0,c.5,2i.6,18.4,1z.9,w.0,d.3,d.3,2.2,17.1,6.a,19.3,r.5,c.2,1r.1,1u.0,u.1,c.5,b.5,f.1,w.1c,26.2,1c.0,39.7,1p.2,g.2,1p.6,18.1,c.7,18.4,ev.1,7.1,13.1,7.1,9.0,2.0,2.0,2.0,w.1,1i.0,g.0,f.1,7.0,k.1,4.0,a.g,p.7,1c.g,3.1,s.0,e.2,y.e,y.e,3x.3,ig.o,c.k,1ed.1,x.0,9q.4,1a.0,2.4,2.1,1l.6,3.d,p.8,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,3j.x,r.0,2i.b,5z.p,d.4,1s.0,2f.1,2w.4,18.0,2n.0,2d.b,1c.0,mlq.2,1k.8,9p.j,55.7,5o.4,3.0,2.0,6.n,1o.2,b.5,1l.7,1z.7,d.5,39.a,v.2,27.0,c.3,y.0,1k.8,f.1,b.1,2w.n,t.9,7.1,7.1,7.8,8.0,8.0,1p.3,3j.1,b.5,8md.b,o.3,1e.6ir,a7.1,2z.11,8.b,6.4,r.0,6.0,2.0,3.0,3.0,3i.f,ce.1,1j.6,2.v,17.5,1g.0,k.0,5.3,6.0,3s.3,5b.2,7.1,7.1,7.1,4.2,8.0,8.c,3.1,d.0,r.0,k.0,3.0,g.1,f.x,3g.4,4.3,1a.2,2h.0,e.2,2.1a,1b.3l,u.2,1e.e,t.3,11.8,v.4,18.4,v.0,12.3,f.15,4f.1,b.5,11.3,11.3,15.7,1h.a,d.0,g.0,8.0,3.0,c.0,g.0,8.0,3.1u,8o.8,n.9,9.n,7.0,17.0,a.1w,7.1,2.0,19.0,3.2,2.1,o.0,21.7,a.1b,k.0,3.4,y.2,s.4,2.1r,1l.3,l.1,1f.0,3.4,9.0,4.0,u.1,4.3,b.6,a.6,1t.v,14.3,d.8,1j.2,u.1,s.4,r.6,5.b,8.27,22.1i,1g.c,1g.6,1b.7,b.85,w.0,17.0,4.1,3.25,15.7,17.l,r.11,t.j,o.8,27.3,11.8,1r.0,6.c,q.6,b.5,1i.0,j.7,14.8,2p.0,l.a,j.0,19.1s,8.0,2.0,5.0,g.0,c.5,1o.4,b.5,5.0,9.1,3.1,n.0,8.0,3.0,6.0,b.1,3.1,4.1,2.5,2.4,8.1,8.2,6.3u,2l.0,6.t,21.7,b.4l,1j.1,13.x,1y.a,b.5,e.i,1n.5,b.1h,s.1,g.3,o.54,1p.2r,2c.b,9.1,2.1,9.0,3.0,v.0,3.1,d.8,b.1x,9.1,1b.1,c.q,21.7,2c.c,22.7a,a.0,1a.0,f.9,u.2,x.1,n.0,f.20,8.0,3.0,19.2,2.0,3.0,a.7,b.5,7.0,3.0,12.0,3.0,7.6,b.8l,q.52,2.e,1f.c,po.2t,34.0,6.a,5h.217,2s.c,ts.34g,g8.6ns,fu.6,w.0,b.3,2a.0,b.5,v.1,7.9,1z.9,b.0,8.0,m.4,k.j3,2k.2s,24.3,1m.6,i.1r,6.a,3.d,4qh.7,yf.15,a.6w6,5.0,8.0,3.0,84.18,4.g,5.7,b1.1s3,30.4,e.2,a.6,b.1,5.3mn,1b.1,o.8,39.1n,6v.9,14.1,23.7,35.k,1z.49,l.b,2g.8,q.3q,2e.0,20.0,3.1,2.1,3.1,5.0,d.0,2.0,8.0,1u.0,5.1,9.0,8.0,t.0,5.0,6.0,2.2,8.0,9h.1,85.1,jj.e,6.0,g.un,w.68,8.0,i.1,8.0,3.0,6.5w,1a.2,f.1,b.3,3.8v,w.g,1n.4,2.yn,8.0,5.0,3.0,g.0,5i.1,h.14,25.3,b.3,3.ls,1x.23,1q.5d,5.0,s.0,3.0,2.1,2.0,b.0,5.0,2.0,2.5,2.3,2.0,2.0,2.0,4.0,3.0,2.1,2.0,2.0,2.0,2.0,2.0,3.0,2.1,5.0,8.0,5.0,5.0,2.0,b.0,i.4,4.0,6.0,i.1f,3.7h,19.3,2t.b,g.1,g.0,g.0,12.9,4v.1j,u.c,19.3,a.6,3.d,7.49,rd.4,h.2,e.2,39.b,2i.6,d.3,2.e,d.3,1l.7,b.5,15.7,v.1,3.25,9h.b,f.1,6.2,6.2,8.8,u.2,c.4,7.9,b.5,9.7,8.8,44.0,1k.10,b.sl,wyp.v,37e.6,67.1,4g3.d,5rm.2e6,f3.15t,3t8.fcms,6p.47bj';
// END unicode tables

/** The unicodedata.unidata_version the tables come from. */
const UNIDATA_VERSION = '14.0.0';

/** code point → digit value of every Nd character (re `\d`, int(), float()). */
const ND_DIGIT = new Map();
for (const z of ND_ZEROS) for (let k = 0; k < 10; k += 1) ND_DIGIT.set(z + k, k);

/** str.isspace(): the ASCII ones (\t \n \v \f \r, \x1c–\x1f, space) + PY_SPACE_HI. */
const PY_SPACE = new Set([0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x1c, 0x1d, 0x1e, 0x1f, 0x20, ...PY_SPACE_HI]);

/** not str.isprintable() above 0x7f as [start, end] pairs (sorted, disjoint). */
const NONPRINT_RANGES = (() => {
  const out = [];
  let prev = 0;
  for (const part of NONPRINT.split(',')) {
    const [d, len] = part.split('.').map((x) => parseInt(x, 36));
    const a = prev + d;
    out.push(a, a + len);
    prev = a + len;
  }
  return Int32Array.from(out);
})();

/** str.isprintable() of one code point. */
function isPrintable(cp) {
  if (cp < 0x7f) return cp >= 0x20;
  let lo = 0;
  let hi = NONPRINT_RANGES.length / 2 - 1;
  while (lo <= hi) {
    const mid = (lo + hi) >> 1;
    if (cp < NONPRINT_RANGES[2 * mid]) hi = mid - 1;
    else if (cp > NONPRINT_RANGES[2 * mid + 1]) lo = mid + 1;
    else return false;
  }
  return true;
}

/** str.isspace() of one code point. */
const isSpace = (cp) => PY_SPACE.has(cp);

/** Digit value of an Nd code point (unicodedata.decimal), or -1. */
const digitValue = (cp) => (ND_DIGIT.has(cp) ? ND_DIGIT.get(cp) : -1);

/** Python's `\d` (any Nd digit of the bot's Unicode database) as a JS character class body (`u` flag). */
const ND_CLASS = ND_ZEROS.map((z) => `\\u{${z.toString(16)}}-\\u{${(z + 9).toString(16)}}`).join('');

module.exports = {
  UNIDATA_VERSION, ND_ZEROS, ND_DIGIT, PY_SPACE, isPrintable, isSpace, digitValue, ND_CLASS,
};
