/**
 * edge.test.js — SMC ADVERSARIAL / EDGE cases the golden sweep cannot see (spec review of M4).
 *
 * fixtures/edge_frames.json + fixtures/edge_expected.json are produced by fixtures/gen_edge_expected.py
 * with the bot's own Python code (pinned venv): slices of the golden candles at a signal bar, mutated
 * into degenerate frames (HTF < 30 bars, empty / 1 / 2 / 21-bar MTF, LTF=None, NaN volume, flat
 * candles = zero ATR, zero prices, NaN high/low/close, tiny and huge price scales), replayed under the
 * whole user-config space (relaxed momentum mode, high_wr_mode, every tf_key group + unknown key,
 * direction / toggles incl. the lowercase quirk, WICK_TOUCH, P/D, MTF check, retrace depths, hard
 * volume filter, vol_mult / vol_len oddities, every analysis-key field) and symbol classes (memcoin
 * keyword substrings, BTC/ETH majors, lowercase, empty).
 *
 * For every case the JS must reproduce, after the fixture rounding r10 (= GOLDEN_STRICT):
 *   - the scanner's config derivation (cfg_obj, analysis key, build kwargs, allowed dirs);
 *   - the analysis digest (make_golden._smc_digest) incl. `error` strings;
 *   - score_bullish / score_bearish, calculate_levels for both directions;
 *   - build_smc_signal (signal or None, or the same exception), rr_ladder, ctx gate;
 *   - the scanner post-build direction filters (§6.5).
 */
import { describe, it, expect } from 'vitest';
import fs from 'fs';
import path from 'path';
import { Frame } from '../../strategies/common/frame.js';
import { r10, fp } from '../../strategies/common/pyfmt.js';
import { pyRound } from '../../strategies/common/pyround.js';
import { calculateLevels } from '../../strategies/smc/levels.js';
import { scoreBullish, scoreBearish } from '../../strategies/smc/signalBuilder.js';
import { smcDigest } from '../../strategies/smc/analyzer.js';
import smcUserCfg from '../../strategies/smc/smcUserCfg.js';
import smc from '../../strategies/smc/index.js';
import prodPython from '../common/prodPython.js';
import compare from '../golden/compare.js';

const FIX = path.join(path.dirname(new URL(import.meta.url).pathname), 'fixtures');
const FRAMES = JSON.parse(fs.readFileSync(path.join(FIX, 'edge_frames.json'), 'utf8'));
const EXP = JSON.parse(fs.readFileSync(path.join(FIX, 'edge_expected.json'), 'utf8'));
const CASES = Object.fromEntries(EXP.cases.map((c) => [c.name, c]));

/** bars with null (= NaN in the generator) → Frame; an empty list → an empty frame. */
function frameOf(bars) {
  const n = bars.length;
  const cols = { t: new Float64Array(n), o: new Float64Array(n), h: new Float64Array(n), l: new Float64Array(n), c: new Float64Array(n), v: new Float64Array(n) };
  const keys = ['t', 'o', 'h', 'l', 'c', 'v'];
  for (let i = 0; i < n; i++) for (let j = 0; j < 6; j++) cols[keys[j]][i] = bars[i][j] === null ? NaN : bars[i][j];
  return Frame.fromColumns(cols);
}

const FRAME_CACHE = new Map();
function framesOf(key) {
  if (!FRAME_CACHE.has(key)) {
    const f = FRAMES.frames[key];
    FRAME_CACHE.set(key, { htf: frameOf(f.htf), mtf: frameOf(f.mtf), ltf: frameOf(f.ltf) });
  }
  return FRAME_CACHE.get(key);
}

/** r10 applied recursively (numbers only; non-finite → null like the generator). */
function r10Deep(x) {
  if (typeof x === 'number') return r10(x);
  if (Array.isArray(x)) return x.map(r10Deep);
  if (x && typeof x === 'object') return Object.fromEntries(Object.entries(x).map(([k, v]) => [k, r10Deep(v)]));
  return x;
}

/** Only the keys the Python dict has are compared (JS levels carry the diagnostic liq_info). */
function pickKeys(actual, expected) {
  if (actual === null || expected === null || typeof expected !== 'object' || Array.isArray(expected)) return actual;
  const out = {};
  for (const k of Object.keys(expected)) out[k] = pickKeys(actual[k], expected[k]);
  return out;
}

const SIGNAL_KEYS = ['symbol', 'direction', 'score', 'grade', 'entry_low', 'entry_high', 'entry', 'sl', 'tp1', 'tp2', 'tp3',
  'rr', 'risk_pct', 'confirmations', 'narrative', 'session', 'tf_htf', 'tf_mtf', 'tf_ltf', 'mode_tag'];

function runCase(c) {
  const fr = framesOf(c.frames);
  const ucfg = smcUserCfg.fromOverrides(c.user_cfg);
  const bc = smcUserCfg.builderConfig(ucfg, {
    highWrMode: c.high_wr_mode, relaxedMode: c.relaxed, smcLongActive: c.smc_long_active, smcShortActive: c.smc_short_active,
  });
  const run = () => smc.evaluate({ symbol: c.symbol, dfHtf: fr.htf, dfMtf: fr.mtf, dfLtf: c.ltf_none ? null : fr.ltf, builderCfg: bc });
  return { ucfg, bc, run };
}

describe('SMC edge fixture — provenance', () => {
  it('was generated by the pinned venv on the golden candle slices', () => {
    expect(EXP.cases.length).toBeGreaterThan(100);
    expect(EXP.python).toMatch(prodPython.PROD_PYTHON);
    expect(EXP.pandas).toMatch(/^\d/);
    expect(Object.keys(FRAMES.frames).length).toBeGreaterThan(30);
  });
  it('_SMC_TF_MAP and SMCUserCfg() defaults are the bot values', () => {
    expect(smcUserCfg.SMC_TF_MAP).toEqual(EXP.tf_map);
    expect(smcUserCfg.defaults()).toEqual(EXP.defaults);
    expect(smcUserCfg.FIELD_NAMES).toEqual(Object.keys(EXP.defaults));   // dataclass order
  });
  it('relax_confirmations / relax_min_rr in relaxed mode: max(2, x−1) / max(1.5, x−0.5)', () => {
    for (const [x, rc, rr] of EXP.relax_table.rows) {
      expect(smcUserCfg.relaxConfirmations(x), `relax_confirmations(${x})`).toBe(rc);
      expect(smcUserCfg.relaxMinRr(x / 2 + 0.5), `relax_min_rr(${x / 2 + 0.5})`).toBe(rr);
      expect(smcUserCfg.relaxConfirmations(x, false)).toBe(x);
      expect(smcUserCfg.relaxMinRr(x, false)).toBe(x);
    }
  });
  it('[SMC-VOL-GATE] per-user volume gate table', () => {
    for (const [minVol, coinVol, want] of EXP.vol_gate) {
      const ucfg = smcUserCfg.fromOverrides({ min_volume_usdt: minVol });
      expect(smc.passesVolumeGate(ucfg, coinVol), `min=${minVol} coin=${coinVol}`).toBe(want);
    }
  });
  it('tf_key lookups are own-key only (Python dict semantics): "constructor" and "5m" fall back to the 1H group', () => {
    expect(smcUserCfg.tfGroup('constructor')).toEqual(EXP.tf_map['1H']);
    expect(smcUserCfg.tfGroup('__proto__')).toEqual(EXP.tf_map['1H']);
    expect(smcUserCfg.tfGroup('5m')).toEqual(EXP.tf_map['1H']);
    expect(smcUserCfg.tfGroup('4H')).toEqual(EXP.tf_map['4H']);
    // from_json keeps dataclass fields only — inherited object keys are not fields
    const cfg = smcUserCfg.fromJson('{"constructor": 1, "toString": 2, "tf_key": "4H", "nope": 3}');
    expect(Object.keys(cfg)).toEqual(Object.keys(EXP.defaults));
    expect(cfg.tf_key).toBe('4H');
    expect(Object.keys(smcUserCfg.fromOverrides({ hasOwnProperty: 1, min_rr: 3 }))).toEqual(Object.keys(EXP.defaults));
  });
});

describe('SMC edge cases — scanner config derivation (cfg_obj / analysis key / build kwargs / dirs)', () => {
  for (const c of EXP.cases) {
    it(c.name, () => {
      const { bc } = runCase(c);
      const d = c.derived;
      expect(r10Deep(bc.cfg)).toEqual(d.cfg);
      expect(bc.analysisKey).toEqual(d.analysis_key);
      expect(bc.pdFilter).toEqual(d.pd_filter);
      expect(bc.mtfCheck).toEqual(d.mtf_check);
      expect(bc.buildKwargs).toEqual(d.build_kwargs);
      expect(bc.buildKwargs.allowed_dirs).toEqual(d.dirs);
      expect(bc.buildKwargs.allowed_dirs.length === 0).toBe(d.skip_user);
    });
  }
});

describe('SMC edge cases — analysis digest, scores, levels, signal vs Python', () => {
  for (const c of EXP.cases) {
    it(`${c.name}${c.signal ? ` → ${c.signal.direction} ${c.signal.score}` : c.analysis_error ? ' → analysis error' : ' → no signal'}`, () => {
      const { ucfg, bc, run } = runCase(c);
      if (c.build_exception) {
        expect(run).toThrow();
        return;
      }
      const out = run();
      const analysis = out.analysis;
      // analysis layer
      expect(analysis.error).toEqual(c.analysis_error);
      expect(out.analysis.squeeze_score).toBe(c.squeeze_score);
      const digestDiffs = compare.compareDigest(smcDigest(analysis), c.digest);
      expect(digestDiffs, compare.formatDiffs(digestDiffs)).toEqual([]);
      expect(r10Deep(smcDigest(analysis))).toEqual(c.digest);
      // scoring (raw 0..8 + labels) and levels for both directions
      const volMult = bc.cfg.VOL_MULT;
      for (const [d, fn] of [['LONG', scoreBullish], ['SHORT', scoreBearish]]) {
        const want = c.scores[d];
        if (typeof want === 'string') {
          expect(() => fn(analysis, volMult), `${d} score raises`).toThrow();
        } else {
          const got = fn(analysis, volMult);
          expect([got.score, got.confirmations], `${d} score`).toEqual(want);
        }
        const wantL = c.levels[d];
        if (typeof wantL === 'string') {
          expect(() => calculateLevels(analysis, d, bc.cfg), `${d} levels raise`).toThrow();
        } else if (wantL === null) {
          expect(calculateLevels(analysis, d, bc.cfg), `${d} levels`).toBeNull();
        } else {
          expect(r10Deep(pickKeys(calculateLevels(analysis, d, bc.cfg), wantL)), `${d} levels`).toEqual(wantL);
        }
      }
      // the signal
      if (c.signal === null) {
        expect(out.signal).toBeNull();
        return;
      }
      expect(out.signal).not.toBeNull();
      const sig = Object.fromEntries(SIGNAL_KEYS.map((k) => [k, out.signal[k]]));
      expect(Object.keys(sig)).toEqual(Object.keys(c.signal));
      expect(r10Deep(sig)).toEqual(c.signal);
      expect(out.signal.rr_ladder).toEqual(c.rr_ladder);
      expect(out.signal.passes_ctx_gate).toBe(c.passes_ctx_gate);
      expect(out.signal.squeeze_score).toBe(c.squeeze_score);
      expect(smc.passesUserDirection(out.signal, ucfg, c.smc_long_active, c.smc_short_active)).toBe(c.post_direction_ok);
      for (const k of ['rr', 'risk_pct']) expect(pyRound(out.signal[k], compare.ROUNDED_FIELDS[k])).toBe(out.signal[k]);
    });
  }
});

describe('SMC edge cases — pinned behaviours (what the cases prove)', () => {
  it('degenerate frames: empty MTF / LTF → pandas IndexError captured as analysis.error; zero prices → ZeroDivisionError', () => {
    expect(CASES.mtf_empty_default.analysis_error).toBe('single positional indexer is out-of-bounds');
    expect(CASES.ltf_empty_default.analysis_error).toBe('single positional indexer is out-of-bounds');
    expect(CASES.zero_low_htf_default.analysis_error).toBe('float division by zero');      // equal-level clustering on a 0 swing
    expect(CASES.zero_low_htf_one_default.analysis_error).toBeNull();                       // a single 0 swing never divides
    expect(CASES.zero_high_ltf_default.analysis_error).toBe('float division by zero');     // bullish FVG with gap_low 0
    expect(CASES.zero_high_ob_default.analysis_error).toBe('float division by zero');      // impulse FVG of the bull OB
    for (const n of ['mtf_empty_default', 'ltf_empty_default', 'zero_low_htf_default', 'zero_high_ltf_default', 'zero_high_ob_default']) {
      expect(CASES[n].signal, n).toBeNull();
      expect(runCase(CASES[n]).run().signal, n).toBeNull();
    }
    // an analysis error stops the pipeline where Python raised: ATR / volume / P-D stay at their init values
    const z = runCase(CASES.zero_high_ob_default).run().analysis;
    expect(z.atr).toBe(0.0);
    expect(z.pd_zone).toEqual({});
  });
  it('HTF below 30 bars → RANGING / no swings / NEUTRAL P-D, OBs and FVGs still found; 30 bars is enough', () => {
    expect(CASES.htf29_default.digest.n_swing_highs).toBe(0);
    expect(CASES.htf29_default.digest.pd_zone).toEqual({ zone: 'NEUTRAL', position_pct: 50.0 });
    expect(CASES.htf29_default.signal).not.toBeNull();
    expect(CASES.htf30_default.digest.n_swing_highs).toBeGreaterThan(0);
  });
  it('MTF with 1 / 2 bars: no OB (impulse search needs 2 closes), vol_ratio 0 below VOL_LEN+2 bars, squeeze 0 below 71', () => {
    expect(CASES.mtf_1_default.digest.bull_ob.found).toBe(false);
    expect(CASES.mtf_1_default.digest.vol_ratio).toBe(0.0);
    expect(CASES.mtf_21_default.digest.vol_ratio).toBe(0.0);     // 21 < 20 + 2
    expect(CASES.mtf_22_default.digest.vol_ratio).toBeGreaterThan(0);
    expect(CASES.mtf_22_default.squeeze_score).toBe(0);
    expect(CASES.btc_vollen_toobig.digest.vol_ratio).toBe(0.0);   // VOL_LEN 149 on a 150-bar frame
    expect(CASES.btc_vollen_big.digest.vol_ratio).toBeGreaterThan(0);
  });
  it('NaN volume: last bar NaN → vol_ratio NaN, c6 label prints "nan", hard volume filter does NOT block (NaN < x is False)', () => {
    expect(CASES.nan_vol_last_default.digest.vol_ratio).toBeNull();
    expect(CASES.nan_vol_last_default.scores.SHORT[1][5][0]).toMatch(/^Объём: nan× ≥ 1\.2× среднего$/);
    expect(CASES.nan_vol_last_default.scores.SHORT[1][5][1]).toBe(false);
    expect(CASES.nan_vol_last_volfilter.signal).not.toBeNull();
    // NaN inside the window is skipped by pandas mean; all-NaN → avg NaN → ratio 0
    expect(CASES.nan_vol_win_default.digest.vol_ratio).toBeGreaterThan(0);
    expect(CASES.nan_vol_all_default.digest.vol_ratio).toBe(0.0);
    expect(CASES.zero_vol_all_default.digest.vol_ratio).toBe(0.0);
  });
  it('flat candles: zero ATR → no ATR floor, no OB on a fully flat MTF, a flat tail keeps the structure', () => {
    expect(CASES.flat_mtf_default.digest.atr).toBe(0.0);
    expect(CASES.flat_mtf_default.digest.bull_ob.found).toBe(false);
    expect(CASES.flat_mtf_default.signal).toBeNull();
    expect(CASES.flat_all_default.digest.n_swing_highs).toBeGreaterThan(0);   // every bar of a plateau is a swing
    expect(CASES.flat_all_default.digest.trend).toBe('RANGING');
    expect(CASES.flat_tail_default.signal).not.toBeNull();
  });
  it('NaN high/low on the last MTF bar: nothing is mitigated, no sweep, no signal; NaN inside HTF/LTF only drops the affected swings/FVGs', () => {
    expect(CASES.nan_mtf_last_hl_default.signal).toBeNull();
    expect(CASES.nan_mtf_last_close_default.signal).toBeNull();
    expect(CASES.nan_htf_mid_default.signal).not.toBeNull();
    expect(CASES.nan_ltf_some_default.signal).not.toBeNull();
  });
  it('price scale: tiny prices use _fp with log10 decimals, huge prices use "{:,.0f}" thousands grouping', () => {
    expect(CASES.tiny_default.signal.narrative).toMatch(/на уровне 0\.0\d+ —/);
    expect(CASES.huge_default.signal.narrative).toMatch(/\d{1,3},\d{3},\d{3}/);
    expect(CASES.huge_doge_default.signal.narrative).toMatch(/\d,\d{3}/);
    expect(CASES.tiny_eth_default.signal.narrative).toMatch(/ордер-блок 0\.000\d+–0\.000\d+ /);   // 7 decimals, zeros stripped
  });
  it('tf_key groups only change the TF strings (narrative + record); unknown / prototype keys fall back to the 1H group', () => {
    const [d, m15, h4, unk, proto] = ['btc_default', 'btc_tf15m', 'btc_tf4H', 'btc_tf_unknown', 'btc_tf_proto'].map((n) => CASES[n].signal);
    expect([m15.tf_htf, m15.tf_mtf, m15.tf_ltf]).toEqual(['1H', '15m', '15m']);
    expect([h4.tf_htf, h4.tf_mtf, h4.tf_ltf]).toEqual(['1D', '4H', '1H']);
    expect(m15.narrative).toMatch(/^На 1H /);
    expect(m15.narrative).toMatch(/15m-свеча/);
    expect(h4.narrative).toMatch(/^На 1D /);
    expect(h4.narrative).toMatch(/на 4H — зону/);
    expect(h4.narrative).toMatch(/1H-свеча/);
    expect(unk.narrative).toBe(d.narrative);
    expect(proto.narrative).toBe(d.narrative);
    expect(CASES.btc_tf_proto.derived.build_kwargs.tf_htf).toBe('4H');
  });
  it('relaxed momentum mode: MIN_CONFIRMATIONS = max(2, x−1), MIN_RR = max(1.5, x−0.5), then high_wr_mode lifts confirmations back to ≥ 4', () => {
    expect(CASES.btc_relaxed.derived.cfg.MIN_CONFIRMATIONS).toBe(2);
    expect(CASES.btc_relaxed.derived.cfg.MIN_RR).toBe(1.5);
    expect(CASES.btc_relaxed_minconf2.derived.cfg.MIN_CONFIRMATIONS).toBe(2);
    expect(CASES.btc_relaxed_minconf5_rr3.derived.cfg.MIN_CONFIRMATIONS).toBe(4);
    expect(CASES.btc_relaxed_minconf5_rr3.derived.cfg.MIN_RR).toBe(2.5);
    expect(CASES.btc_relaxed_rr15.derived.cfg.MIN_RR).toBe(1.5);
    expect(CASES.btc_relaxed_hwr.derived.cfg.MIN_CONFIRMATIONS).toBe(4);
    expect(CASES.btc_relaxed_hwr.derived.pd_filter).toBe(true);
    expect(CASES.btc_relaxed_hwr.derived.mtf_check).toBe(true);
    // the relaxed values are what the gates use: a 4/8 signal passes min_conf 5 only when relaxed
    expect(CASES.btc_minconf5.signal).toBeNull();
    expect(CASES.btc_relaxed_minconf5_rr3.signal).not.toBeNull();
  });
  it('high_wr_mode: MIN_CONFIRMATIONS = max(x, 4) with P/D + MTF forced on (the analysis key is computed before the override)', () => {
    expect(CASES.btc_hwr.derived.cfg.MIN_CONFIRMATIONS).toBe(4);
    expect(CASES.btc_hwr_minconf2.derived.cfg.MIN_CONFIRMATIONS).toBe(4);
    expect(CASES.btc_hwr_minconf5.derived.cfg.MIN_CONFIRMATIONS).toBe(5);
    expect(CASES.btc_hwr.derived.analysis_key).toEqual(CASES.btc_default.derived.analysis_key);
    expect(CASES.doge_hwr.signal).toBeNull();   // 3/8 memcoin setup cannot reach 4
  });
  it('direction / toggles: ucfg.direction narrows before scoring, toggles filter, an empty set skips the user, "long" (lowercase) builds but is rejected afterwards', () => {
    expect(CASES.btc_dir_long.derived.dirs).toEqual(['LONG']);
    expect(CASES.btc_dir_long.signal).toBeNull();          // the SHORT setup is never tried
    expect(CASES.btc_dir_short.signal.direction).toBe('SHORT');
    expect(CASES.btc_flag_short.derived.dirs).toEqual(['SHORT']);
    expect(CASES.btc_dir_long_flag_short.derived.skip_user).toBe(true);
    expect(CASES.btc_dir_short_flag_long.derived.skip_user).toBe(true);
    expect(CASES.btc_dir_lower.derived.dirs).toEqual(['LONG', 'SHORT']);
    expect(CASES.btc_dir_lower.signal).not.toBeNull();
    expect(CASES.btc_dir_lower.post_direction_ok).toBe(false);   // QUIRK: raw compare "SHORT" != "long"
    expect(CASES.btc_dir_short.post_direction_ok).toBe(true);
    expect(CASES.btc_flag_both.post_direction_ok).toBe(true);
  });
  it('style filters: WICK_TOUCH lifts F1, P/D blocks the wrong half, retrace depth 1.0 (and int 1) needs the full OB, hard volume filter at 5× blocks', () => {
    expect(CASES.btc_wick_touch.signal.mode_tag).toBe('⚡ Aggressive');
    expect(CASES.btc_pd_mtf_wick.signal.mode_tag).toBe('🎯 Conservative');
    expect(CASES.btc_retrace1.signal).toBeNull();
    expect(CASES.btc_retrace_int1.signal).toBeNull();
    expect(CASES.btc_retrace05.signal).not.toBeNull();
    expect(CASES.btc_volfilter_high.signal).toBeNull();
    expect(CASES.btc_volfilter_low.signal.score).toBe(5);   // vol_mult 0.5 turns c6 on → A+
    expect(CASES.btc_volmult_int.signal.confirmations[5][0]).toMatch(/≥ 2\.0× среднего$/);   // float(2) → "2.0"
    expect(CASES.btc_volmult_zero.signal.confirmations[5][0]).toMatch(/≥ 1\.2× среднего$/);  // 0 → `or 1.2`
  });
  it('analysis-key fields: vol_len 3 → effective 5, 0 → 20, 7.9 → int 7; the six-field key selects the shared analysis', () => {
    expect(CASES.btc_vollen3.derived.analysis_key[5]).toBe(3);
    expect(CASES.btc_vollen0.derived.analysis_key[5]).toBe(20);
    expect(CASES.btc_vollen_float.derived.analysis_key[5]).toBe(7);
    expect(CASES.btc_obage_float.derived.analysis_key[3]).toBe(50);
    expect(CASES.btc_key_all_off.derived.analysis_key).toEqual([false, false, false, 20, false, 5]);
    expect(CASES.btc_fvg_off.digest.bull_fvg).toBeNull();
    expect(CASES.btc_fvg_off.signal.score).toBe(3);
    expect(CASES.btc_ltf_none.digest.n_fvgs).not.toBe(CASES.btc_default.digest.n_fvgs);   // FVG on the MTF instead
  });
  it('symbol classes: memcoin keywords are substrings (ACTA, MEMEFI, BOOKOFMEME, FACTORY → cap 3), ETHFI/ETHMEME are majors, case-insensitive, "" is an alt', () => {
    for (const s of ['PEPE-USDT-SWAP', '1000SATS-USDT-SWAP', 'ACTA-USDT-SWAP', 'MEMEFI-USDT-SWAP', 'pepe-usdt-swap', 'BOOKOFMEME-USDT-SWAP', 'FACTORY-USDT-SWAP', 'ETHMEME-USDT-SWAP']) {
      expect(CASES[`btc_sym_${s}`].signal.score, s).toBe(3);
      expect(smc.isMemcoin(s), s).toBe(true);
    }
    expect(CASES['btc_sym_ETHFI-USDT-SWAP'].signal.score).toBe(4);
    expect(CASES['btc_sym_SOL-USDT-SWAP'].signal.score).toBe(4);
    expect(CASES.btc_sym_empty.signal.score).toBe(4);
    expect(smc.isMajor('ETHMEME-USDT-SWAP')).toBe(true);
  });
  it('_fp: log10-driven decimals agree with CPython around every power of ten (V8 Math.log10 differs in the last ulp elsewhere, never at the floor)', () => {
    // python: [(repr(v), _fp(v)) for k in 1..12 for v in (10**-k and its nextafter / ±1e-9 neighbours, 5.5·10**-k)] + magnitudes
    expect(EXP.fp_table.length).toBeGreaterThan(70);
    for (const [v, want] of EXP.fp_table) expect(fp(Number(v)), v).toBe(want);
  });
});
