/**
 * part2.test.js — the LEVELS part-2 modules (M6) against the bot's own code
 * (fixtures/part2_expected.json, generated by fixtures/gen_part2.py with the pinned venv):
 *
 *  1. part2_locals: every golden bar that reached part 2 (564 bars: 55 signals + sl_risk / rr /
 *     quality_hwr / levels_filter rejects) — the locals of the bot's `_do_analyze` frame at return
 *     (sl before/after magnets, magnet info, risk, class flags, structural TPs, scale, TPs at the
 *     reject stage, rr_actual, rr_score, corr, divergence, LVN, HTF, quality, reasons, checklist,
 *     explanation, filter verdict) must equal the JS diagnostics BIT-FOR-BIT, stage by stage.
 *  2. adjust_sl_for_magnets on 306 random/boundary cases; coin classes; levels_stars / stars_str;
 *     relax_min_rr / relax_min_quality; detect_atr_breakout hits/misses/cooldown and the relaxed-mode
 *     fallback SignalResult of analyze().
 *  3. Spec-derived unit tests: HIGH_WR ladder + filter order (and the golden conservative signals),
 *     minimum-stop classes, the 18-step quality accumulation order, checklist, levels_filters modes,
 *     CooldownState, createIndicator stats, scanner post-steps, explanation branches, SignalResult.
 */
import { describe, it, expect } from 'vitest';
import fs from 'fs';
import path from 'path';
import load from '../golden/load.js';
import compare from '../golden/compare.js';
import { Frame } from '../../strategies/common/frame.js';
import F from '../../strategies/common/pyfmt.js';
import L from '../../strategies/levels/index.js';
import prodPython from '../common/prodPython.js';

const FIX = path.join(path.dirname(new URL(import.meta.url).pathname), 'fixtures', 'part2_expected.json');
const EXP = JSON.parse(fs.readFileSync(FIX, 'utf8'));

it('fixtures/part2_expected.json comes from the production interpreter (CPython 3.11)', () => {
  expect(EXP.python).toMatch(prodPython.PROD_PYTHON);
});
const { loadFrames, loadFrame, barInputs, loadExpected } = load;
const { numbersClose } = compare;
const { r10 } = F;

/** Exact comparison with the fixture encoding (null = NaN/None; floats repr → bit-for-bit). */
function same(a, b) {
  if (b === null || b === undefined) return a === null || a === undefined || (typeof a === 'number' && Number.isNaN(a));
  if (typeof b === 'number') return typeof a === 'number' && (Object.is(a, b) || a === b);
  if (Array.isArray(b)) return Array.isArray(a) && a.length === b.length && b.every((x, i) => same(a[i], x));
  if (typeof b === 'object') return a !== null && typeof a === 'object' && Object.keys(b).every((k) => same(a[k], b[k]));
  return a === b;
}

function cfgOf(variantName) {
  const v = loadExpected('levels').variants[variantName];
  return L.cfgToInd(L.tradeCfg(v.trade_cfg), v.high_wr_mode);
}

describe('part 2 locals of the bot _do_analyze frame (564 late-stage golden bars)', () => {
  it('every captured local equals the JS diagnostic at the same stage, bit-for-bit', () => {
    const failures = [];
    const stages = {};
    const cfgs = {};
    for (const rec of EXP.part2_locals) {
      const cfg = cfgs[rec.variant] || (cfgs[rec.variant] = cfgOf(rec.variant));
      const frames = loadFrames(rec.symbol);
      const b = barInputs(frames, rec.i);
      const res = L.doAnalyze(rec.symbol, b.df, cfg.USE_HTF_FILTER ? b.dfHtf1d : null, b.dfBtc, b.dfEth, cfg, { relaxed: false, regime: null });
      const stage = res.signal ? 'signal' : res.rejectReason;
      stages[stage] = (stages[stage] || 0) + 1;
      const tag = `${rec.symbol}/${rec.variant}/${rec.i}`;
      if (stage !== rec.stage) { failures.push(`${tag}: stage ${stage} != ${rec.stage} (${res.reason})`); continue; }
      const loc = rec.locals;
      const tps = res.final || res.highWr || res.targets || {};
      const map = {
        entry: () => res.part1.pro.cNow,
        sl: () => res.stop.sl,
        _sl_before_lq: () => res.stop.slBeforeMagnets,
        _lq_info: () => res.stop.magnetInfo,
        risk: () => res.stop.risk,
        risk_pct_raw: () => res.stop.riskPctRaw,
        is_memcoin: () => res.stop.memcoin,
        is_major: () => res.stop.major,
        _legacy_sl_dist: () => res.stop.stop.legacyDist,
        _new_sl_dist: () => res.stop.stop.newDist,
        _regime_mult: () => 1.0,
        stp1: () => res.targets.structural[0],
        stp2: () => res.targets.structural[1],
        stp3: () => res.targets.structural[2],
        _tp_scale: () => res.targets.scale,
        _tp1_mech_rr: () => res.targets.tp1MechRr,
        tp1: () => tps.tp1,
        tp2: () => tps.tp2,
        tp3: () => tps.tp3,
        rr_actual: () => res.rrActual,
        _effective_min_rr: () => (res.effectiveMinRr === undefined ? cfg.MIN_RR : res.effectiveMinRr),
        risk_pct: () => res.riskPct,
        rr_score: () => res.rrScore,
        corr_data: () => res.corrData,
        diverg_ok: () => res.divergOk,
        diverg_label: () => res.divergLabel,
        has_lvn_path: () => res.hasLvnPath,
        htf_ok: () => res.htfOk,
        quality: () => res.quality.quality,
        reasons: () => res.quality.reasons,
        checklist: () => res.checklist,
        explanation: () => res.final.explanation,
        _lf_enf: () => (res.rejectReason === 'levels_filter' ? String(res.reason).replace(/^filter_/, '') : null),
        _lf_shadow: () => res.shadowFilters,
      };
      for (const [k, want] of Object.entries(loc)) {
        if (k === '_hour') continue;
        let got;
        try { got = map[k](); } catch (e) { failures.push(`${tag}: ${k} not available in the JS diagnostics (${e.message})`); continue; }
        if (!same(got, want)) failures.push(`${tag} [${stage}] ${k}: ${JSON.stringify(got)} != ${JSON.stringify(want)}`);
      }
      if (stage === 'signal') {
        for (const k of ['sl', 'tp1', 'tp2', 'tp3', 'risk_pct', 'rr_score', 'quality', 'reasons', 'explanation']) {
          const sk = k === 'explanation' ? 'human_explanation' : k;
          if (!same(res.signal[sk], loc[k])) failures.push(`${tag}: signal.${sk} differs from the local ${k}`);
        }
      }
    }
    if (failures.length) throw new Error(`${failures.length} mismatches:\n${failures.slice(0, 20).join('\n')}`);
    expect(stages).toEqual({ signal: 55, sl_risk: 32, rr: 283, quality_hwr: 47, levels_filter: 147 });
  });
});

describe('adjustSlForMagnets vs liquidity_sl_adjuster.adjust_sl_for_magnets', () => {
  it('306 random / boundary cases (exact-edge magnets, zero prices, custom percentages)', () => {
    let adjusted = 0; let capped = 0;
    for (const c of EXP.magnets) {
      const kw = { dangerZonePct: c.kw.danger_zone_pct, extensionBufPct: c.kw.extension_buf_pct, maxExtensionPct: c.kw.max_extension_pct };
      for (const k of Object.keys(kw)) if (kw[k] === undefined) delete kw[k];
      const [sl, info] = L.adjustSlForMagnets(c.sl, c.direction, c.magnets, kw);
      expect(same(sl, c.new_sl)).toBe(true);
      expect(info).toEqual(c.info);
      if (info.adjusted) adjusted++;
      if (info.capped) capped++;
    }
    expect(adjusted).toBeGreaterThan(50);
    expect(capped).toBeGreaterThan(0);
  });
  it('only widens; a string magnet that does not parse → invalid_magnets', () => {
    expect(L.adjustSlForMagnets(100, 'LONG', [99.8])[0]).toBeLessThan(100);
    expect(L.adjustSlForMagnets(100, 'SHORT', [100.2])[0]).toBeGreaterThan(100);
    expect(L.adjustSlForMagnets(100, 'LONG', ['abc'])[1].reason).toBe('invalid_magnets');
    expect(L.adjustSlForMagnets(100, 'LONG', ['99.8'])[1].adjusted).toBe(true);
  });
});

describe('coin classes (memcoin keywords / BTC-ETH substring), stars, relaxed-mode helpers', () => {
  it('isMemcoin / isMajor equal the bot rule on the symbol table; keyword tuple identical', () => {
    expect([...L.MEMCOIN_KW]).toEqual(EXP.coin_class.keywords);
    for (const r of EXP.coin_class.rows) {
      expect([r.symbol, L.isMemcoin(r.symbol)]).toEqual([r.symbol, r.memcoin]);
      expect([r.symbol, L.isMajor(r.symbol)]).toEqual([r.symbol, r.major]);
    }
  });
  it('levelsStars / starsStr reproduce quality_scale on every input incl. Python float strings', () => {
    for (const r of EXP.stars) {
      const input = r.input;
      if (r.stars !== null) {
        expect([input, L.levelsStars(input)]).toEqual([input, r.stars]);
        expect([input, L.starsStr(L.levelsStars(input))]).toEqual([input, r.text]);
      } else {
        expect([input, L.starsStr(input)]).toEqual([input, r.text]);
      }
    }
    expect(L.levelsStars(6)).toBe(4);      // "A"
    expect(L.levelsStars(8)).toBe(5);      // "A+"
    expect(L.levelsStars(5.99)).toBe(3);
  });
  it('relax_min_rr / relax_min_quality with relaxed mode off and on', () => {
    for (const [x, want] of EXP.relaxed.off.min_rr) expect(L.effectiveMinRr(x, false)).toBe(want);
    for (const [x, want] of EXP.relaxed.on.min_rr) expect(L.effectiveMinRr(x, true)).toBe(want);
    for (const [x, want] of EXP.relaxed.off.min_quality) expect(L.relaxMinQuality(x, false)).toBe(want);
    for (const [x, want] of EXP.relaxed.on.min_quality) expect(L.relaxMinQuality(x, true)).toBe(want);
  });
});

describe('detectAtrBreakout vs momentum_detector.detect_atr_breakout (+ relaxed-mode fallback)', () => {
  it('41 real hits are identical (entry/sl/tp/atr/mult/vol_ratio/reason); misses are null', () => {
    for (const h of EXP.atr_breakout.hits) {
      const df = loadFrame(h.symbol, '1h').slice(0, h.n);
      const got = L.detectAtrBreakout(h.symbol, df, { nowSec: 1e9, lastAlert: new Map() });
      expect(got).not.toBeNull();
      for (const k of Object.keys(h.result)) expect([k, same(got[k], h.result[k])]).toEqual([k, true]);
    }
    for (const m of EXP.atr_breakout.misses) {
      expect(L.detectAtrBreakout(m.symbol, loadFrame(m.symbol, '1h').slice(0, m.n), { nowSec: 1e9, lastAlert: new Map() })).toBeNull();
    }
    expect(L.detectAtrBreakout('X', loadFrame('BTC-USDT-SWAP', '1h').slice(0, 19))).toBeNull();
  });
  it('per-symbol cooldown of 3600 s on the injected map', () => {
    const c = EXP.atr_breakout.cooldown;
    const df = loadFrame(c.symbol, '1h').slice(0, c.n);
    const lastAlert = new Map();
    expect(L.detectAtrBreakout(c.symbol, df, { nowSec: 1e9, lastAlert }) !== null).toBe(c.first_hit);
    expect(L.detectAtrBreakout(c.symbol, df, { nowSec: 1e9, lastAlert }) !== null).toBe(c.second_hit);
    expect(L.detectAtrBreakout(c.symbol, df, { nowSec: 1e9 + 3599, lastAlert })).toBeNull();
    expect(L.detectAtrBreakout(c.symbol, df, { nowSec: 1e9 + 3600, lastAlert })).not.toBeNull();
  });
  it('analyze() in relaxed mode returns the ATR-breakout SignalResult when _do_analyze is None', () => {
    const cfg = L.defaultIndConfig();
    expect(EXP.atr_breakout.fallback.length).toBeGreaterThan(0);
    for (const f of EXP.atr_breakout.fallback) {
      const df = loadFrame(f.symbol, '1h').slice(0, f.n);
      const plain = L.doAnalyze(f.symbol, df, null, null, null, cfg, { relaxed: false });
      expect(plain.signal === null).toBe(f.do_analyze_none);
      const res = L.analyze(f.symbol, df, null, null, null, cfg, { relaxed: true, nowSec: 1e9, breakoutState: new Map(), triggerReason: f.trigger_reason });
      if (f.signal === null) { expect(res.signal).toBeNull(); continue; }
      expect(res.stage).toBe('atr_breakout');
      expect(Object.keys(res.signal)).toEqual(Object.keys(f.signal));
      for (const k of Object.keys(f.signal)) expect([k, same(res.signal[k], f.signal[k])]).toEqual([k, true]);
    }
  });
});

describe('HIGH_WR mode (spec §16)', () => {
  const t0 = Date.UTC(2026, 0, 1, 12, 0, 0);
  const frameAtHour = (h) => Frame.fromBars([[Date.UTC(2026, 0, 1, h, 0, 0), 1, 1, 1, 1, 1]]);
  const base = { signal: 'LONG', isCounter: false, quality: 6, df: frameAtHour(12), entry: 100, risk: 2, tp1: 103, tp2: 104, tp3: 110, bullLocal: true, bearLocal: false };

  it('ladder: tp1 = entry ± 1.5R, tp2/tp3 not closer than 2.5R / 4R (Python max/min)', () => {
    expect(L.highWrLadder('LONG', 100, 2, 104, 110)).toEqual({ tp1: 103, tp2: 105, tp3: 110 });
    expect(L.highWrLadder('LONG', 100, 2, 106, 107)).toEqual({ tp1: 103, tp2: 106, tp3: 108 });
    expect(L.highWrLadder('SHORT', 100, 2, 96, 90)).toEqual({ tp1: 97, tp2: 95, tp3: 90 });
    expect(L.highWrLadder('SHORT', 100, 2, 94, 93)).toEqual({ tp1: 97, tp2: 94, tp3: 92 });
    expect(Object.is(L.highWrLadder('LONG', 0, 0, -0, 0).tp2, -0)).toBe(true);   // max(tp2, 0.0) keeps the first operand
  });
  it('filters in order: counter-trend → stars < 4 → hour outside 08–22 → ladder → local trend', () => {
    expect(L.applyHighWr({ ...base, isCounter: true, quality: 10 }).reason).toBe('hwr_counter_trend');
    expect(L.applyHighWr({ ...base, quality: 5 }).reason).toBe('hwr_stars');
    expect(L.applyHighWr({ ...base, quality: 6 }).reject).toBeNull();
    expect(L.applyHighWr({ ...base, df: frameAtHour(7) }).reason).toBe('hwr_hour');
    expect(L.applyHighWr({ ...base, df: frameAtHour(22) }).reason).toBe('hwr_hour');
    expect(L.applyHighWr({ ...base, df: frameAtHour(8) }).reject).toBeNull();
    expect(L.applyHighWr({ ...base, df: frameAtHour(21) }).reject).toBeNull();
    const bear = L.applyHighWr({ ...base, bullLocal: false, bearLocal: true });
    expect(bear.reason).toBe('hwr_long_in_bear');
    expect([bear.tp1, bear.tp2, bear.tp3]).toEqual([103, 105, 110]);         // ladder applied before the trend check
    const stars = L.applyHighWr({ ...base, quality: 5 });
    expect([stars.tp1, stars.tp2, stars.tp3]).toEqual([103, 104, 110]);       // rejected before the ladder
    expect(L.applyHighWr({ ...base, signal: 'SHORT', tp1: 97, tp2: 96, tp3: 90, bullLocal: true }).reason).toBe('hwr_short_in_bull');
    const ok = L.applyHighWr({ ...base, signal: 'SHORT', tp1: 97, tp2: 96, tp3: 90, bullLocal: false });
    expect([ok.reject, ok.tp1, ok.tp2, ok.tp3]).toEqual([null, 97, 95, 90]);   // tp3 already beyond 4R → kept
    expect(L.applyHighWr({ ...base, df: {} }).reject).toBeNull();            // hour error → swallowed
    expect(L.applyHighWr({ ...base, bullLocal: false, bearLocal: false }).reject).toBeNull();
    void t0;
  });
  it('golden conservative (HIGH_WR) signals carry the ladder: tp1 = entry ± 1.5·risk, tp2 ≥ 2.5R, tp3 ≥ 4R', () => {
    const lv = loadExpected('levels');
    let n = 0;
    for (const sym of Object.keys(lv.fixtures)) {
      for (const s of lv.fixtures[sym].conservative.signals) {
        const sign = s.direction === 'LONG' ? 1 : -1;
        const risk = Math.abs(s.entry - s.sl);
        expect(numbersClose(s.tp1, s.entry + sign * risk * 1.5, 1e-7)).toBe(true);   // fixture values are r10-rounded
        expect(sign * (s.tp2 - s.entry) / risk).toBeGreaterThanOrEqual(2.5 - 1e-6);
        expect(sign * (s.tp3 - s.entry) / risk).toBeGreaterThanOrEqual(4.0 - 1e-6);
        expect(s.is_counter_trend).toBe(false);
        expect(L.levelsStars(s.quality)).toBeGreaterThanOrEqual(4);
        n++;
      }
    }
    expect(n).toBe(12);
  });
});

describe('stops: structural distance, coin-class minimums (spec §10)', () => {
  const cfg = L.defaultIndConfig();   // MAX_RISK_PCT 1.5
  it('distance = max(min(|entry − raw_sl|, entry·MAX_RISK_PCT/100), 0.5·ATR); SL on the entry side', () => {
    // LONG: level 99, zone_buf 0.5, atr 1 → raw 97; |100 − 97| = 3 > cap 1.5 → 1.5
    expect(L.structuralStop('LONG', 100, 99, 0.5, 1, cfg).sl).toBe(98.5);
    // atr 0.2 → raw 98.2, dist 1.8 → cap 1.5
    expect(L.structuralStop('LONG', 100, 99, 0.5, 0.2, cfg).sl).toBe(98.5);
    // level 99.9, buf 0.05, atr 0.02 → raw 99.82, dist 0.18 > floor 0.01 → 0.18
    const raw = (99.9 - 0.05) - 0.02 * 1.5;
    expect(L.structuralStop('LONG', 100, 99.9, 0.05, 0.02, cfg).sl).toBe(100 - Math.abs(100 - raw));
    // floor: level 100, buf 0, atr 2 → raw 97, dist 3 → cap 1.5 → floor 1.0 → 1.5 (max)
    expect(L.structuralStop('LONG', 100, 100, 0, 2, cfg).slDist).toBe(1.5);
    // floor wins: atr 4 → floor 2 > cap 1.5
    expect(L.structuralStop('LONG', 100, 100, 0, 4, cfg).slDist).toBe(2);
    expect(L.structuralStop('SHORT', 100, 101, 0.5, 1, cfg).sl).toBe(101.5);
    const s = L.structuralStop('LONG', 100, 99, 0.5, 1, cfg, { regimeMult: 0.85, slV2Enabled: false });
    expect([s.legacyDist, s.newDist, s.slDist]).toEqual([1.5, 1.275, 1.5]);               // shadow: legacy used
    expect(L.structuralStop('LONG', 100, 99, 0.5, 1, cfg, { regimeMult: 0.85, slV2Enabled: true }).slDist).toBe(1.275);
  });
  it('minimum stop by class: major 0.4 %, memcoin 1.5 %, alt 0.8 %; major checked before memcoin', () => {
    // entry 1000, |risk| = pct·10 (exact decimals → risk/entry·100 is exactly pct for these cases)
    const v = (sym, pct, signal = 'LONG') => L.checkStopValidity(sym, signal, 1000, signal === 'LONG' ? 1000 - pct * 10 : 1000 + pct * 10, 5);
    expect(v('BTC-USDT-SWAP', 0.3).reason).toBe('min_stop_major');
    expect(v('BTC-USDT-SWAP', 0.4).reject).toBeNull();
    expect(v('ETHFI-USDT-SWAP', 0.3).reason).toBe('min_stop_major');
    expect(v('PEPE-USDT-SWAP', 1.2).reason).toBe('min_stop_memcoin');
    expect(v('PEPE-USDT-SWAP', 1.5).reject).toBeNull();
    expect(v('SYNUP01-USDT-SWAP', 0.7).reason).toBe('min_stop_alt');
    expect(v('SYNUP01-USDT-SWAP', 0.8).reject).toBeNull();
    expect(v('WIFETH-USDT-SWAP', 0.3).reason).toBe('min_stop_major');       // both classes: major gate first
    expect(v('WIFETH-USDT-SWAP', 0.5).reason).toBe('min_stop_memcoin');     // then the memcoin gate
    expect(v('WIFETH-USDT-SWAP', 1.6).reject).toBeNull();
    expect(v('SYN', 1.0, 'SHORT').reject).toBeNull();
    expect(L.checkStopValidity('SYN', 'LONG', 100, 100, 1).reason).toBe('sl_above_entry');
    expect(L.checkStopValidity('SYN', 'SHORT', 100, 99, 1).reason).toBe('sl_below_entry');
    expect(L.checkStopValidity('SYN', 'LONG', 100, 99, 10).reason).toBe('min_stop_atr');   // risk 1 < 0.3·10
    expect(L.checkStopValidity('SYN', 'LONG', 100, 99, 0).reject).toBeNull();               // atr 0 → no ATR gate
    expect(L.MIN_STOP_PCT).toEqual({ major: 0.4, memcoin: 1.5, alt: 0.8 });
  });
  it('computeStop: magnets come from the support zones for LONG / resistance zones for SHORT, prices > 0', () => {
    const sup = [{ price: 98.4 }, { price: 0 }, { price: 50 }];
    const res = [{ price: 101.6 }];
    const a = L.computeStop('SYN', 'LONG', 100, 99, 0.5, 1, cfg, sup, res);   // sl 98.5 → magnet 98.4 inside 0.5 % → 98.4·0.999
    expect(a.slBeforeMagnets).toBe(98.5);
    expect(a.sl).toBe(98.4 * (1.0 - 0.10 / 100.0));
    expect(a.magnetInfo).toEqual({ adjusted: true, reason: 'magnet_in_zone_long', target: 98.4, capped: false, n_in_zone: 1 });
    expect(a.reject).toBeNull();
    const b = L.computeStop('SYN', 'SHORT', 100, 101, 0.5, 1, cfg, sup, res);
    expect(b.sl).toBe(101.6 * (1.0 + 0.10 / 100.0));
  });
});

describe('targets (spec §11)', () => {
  const cfg = L.defaultIndConfig();   // TP 2/3/4.5, MIN_RR 2
  it('structural candidates: opposite zones ≥ 0.2 % away, pulled 0.05 %, nearest first', () => {
    const res = [{ price: 100.1 }, { price: 103 }, { price: 101 }, { price: 110 }, { price: 99 }];
    expect(L.findTpLevels('LONG', 100, [], res)).toEqual([101 * (1 - 0.0005), 103 * (1 - 0.0005), 110 * (1 - 0.0005)]);
    expect(L.findTpLevels('LONG', 100, [], [{ price: 100.2 }])).toEqual([null, null, null]);   // not > entry·1.002
    expect(L.findTpLevels('LONG', 100, [], [{ price: 100.2000001 }])[0]).toBe(100.2000001 * (1 - 0.0005));
    const sup = [{ price: 99.9 }, { price: 97 }, { price: 99 }];
    expect(L.findTpLevels('SHORT', 100, sup, [])).toEqual([99 * (1 + 0.0005), 97 * (1 + 0.0005), null]);
    expect(L.findTp1Level('LONG', 100, [], res)).toBe(101);
    expect(L.findTp1Level('SHORT', 100, sup, [])).toBe(99);
  });
  it('ATR scale and the mechanical ladder with the MIN_RR floor; ordering repair; strict order → rr', () => {
    expect([L.tpScale(3.1, 100), L.tpScale(0.9, 100), L.tpScale(2, 100), L.tpScale(1, 0)]).toEqual([1.2, 0.85, 1.0, 1.0]);
    const t = L.assembleTargets('LONG', 100, 1, [null, null, null], cfg, 0.85);
    expect([t.tp1, t.tp2, t.tp3, t.tp1MechRr]).toEqual([102, 100 + 3 * 0.85, 100 + 4.5 * 0.85, 2]);   // TP1 floored at MIN_RR
    const u = L.assembleTargets('LONG', 100, 1, [null, null, null], cfg, 1.2);
    expect([u.tp1, u.tp2, u.tp3]).toEqual([100 + 2 * 1.2, 100 + 3 * 1.2, 100 + 4.5 * 1.2]);
    // structural tp1 above the mechanical tp2 → tp2 repaired with the UNSCALED TP2_RR, tp3 = tp2 + 1.5R
    const v = L.assembleTargets('LONG', 100, 1, [104, null, null], cfg, 0.85);
    expect([v.tp1, v.tp2, v.tp3, v.reject]).toEqual([104, 103, 100 + 4.5 * 0.85, 'rr']);     // tp2 repaired (unscaled 3R), 104 ≥ 103 → order broken → rr
    const w = L.assembleTargets('LONG', 100, 1, [102.5, null, null], cfg, 0.85);
    expect([w.tp1, w.tp2, w.tp3, w.reject]).toEqual([102.5, 100 + 3 * 0.85, 100 + 4.5 * 0.85, null]);   // 102.5 < 102.55 → no repair
    const x = L.assembleTargets('LONG', 100, 1, [102.6, null, null], cfg, 0.85);
    expect([x.tp1, x.tp2, x.tp3, x.reject]).toEqual([102.6, 103, 100 + 4.5 * 0.85, null]);              // tp2 repaired to the unscaled 3R
    const s = L.assembleTargets('SHORT', 100, 1, [null, 96, 95], cfg, 1.0);
    expect([s.tp1, s.tp2, s.tp3, s.reject]).toEqual([98, 96, 95, null]);
    expect(L.rrActual('LONG', 100, 103, 1)).toBe(3);
    expect(L.rrActual('SHORT', 100, 97, 1)).toBe(3);
    expect(L.calculateRrScore('LONG', 100, 99, 102, 103, 104.5)).toBe(2 * 0.5 + 3 * 0.3 + 4.5 * 0.2);
    expect(L.calculateRrScore('LONG', 100, 100, 102, 103, 104)).toBe(0.0);
  });
});

describe('quality accumulation (spec §13) — exact order of the 18 steps', () => {
  const full = {
    sType: 'Отскок от поддержки', instPattern: 'LIQUIDITY_SWEEP', patternBonus: 3, sClass: 1, htfOk: true,
    sZone: { mtf_label: 'MTF', timeframes: ['ltf', 'htf'], has_hvn: true }, isCounter: false, volRatio: 1.5, volMult: 1.0,
    hasLvnPath: true, divergOk: true, divergLabel: '✅ Бычья дивергенция RSI', approachOk: true,
    approachReason: '✅ Снижение объёма на подходе | ✅ Консолидация у уровня', signal: 'LONG', rsiNow: 40,
    corr: { btc_corr: 0.1, eth_corr: 0.2 }, testCount: 1, isDeadSession: true, session: '🌏 Азиатская сессия', rrScore: 1.5, memcoin: true,
  };
  it('all bonuses on: reasons in bot order, 14 − 2 − 1 → clamp 10 → memcoin cap 5', () => {
    const q = L.accumulateQuality(full);
    expect(q.reject).toBeNull();
    expect(q.quality).toBe(5);
    expect(q.reasons).toEqual([
      '✅ Отскок от поддержки',
      '✅ [LIQUIDITY_SWEEP] — паттерн класса A',
      '✅ Уровень класса 1 (Абсолютный)',
      '✅ HTF тренд подтверждает',
      '✅ MTF уровень (2 ТФ)',
      '✅ По локальному тренду',
      '✅ Объём x1.5',
      '✅ Volume Profile узел (HVN)',
      '✅ Чистый путь к цели (LVN)',
      '✅ Бычья дивергенция RSI',
      '✅ ✅ Снижение объёма на подходе | ✅ Консолидация у уровня',   // QUIRK: "✅ " prefix added to a reason that already starts with ✅
      '✅ RSI выходит из перепроданности',
      '✅ Независимое движение (corr < 0.4)',
      '✅ Тест #1 уровня (оптимально)',
      '⚠️ 🌏 Азиатская сессия — низкая ликвидность',
      '⚠️ Взвешенный R:R: 1.50 (ниже 1.8)',
      '⚠️ Мемкоин (повышенный риск)',
    ]);
    expect(L.accumulateQuality({ ...full, memcoin: false, rrScore: 2.0 }).quality).toBe(10);   // 14 clamped
    expect(L.accumulateQuality({ ...full, memcoin: false, rrScore: 2.0, isDeadSession: false }).quality).toBe(10);
  });
  it('points per step and the mid-accumulation rr_score drop', () => {
    const minimal = {
      sType: 'Пробой уровня', instPattern: 'BOUNCE_PLAIN', patternBonus: 0, sClass: 3, htfOk: false, sZone: { has_hvn: false },
      isCounter: true, volRatio: 0.8, volMult: 1.0, hasLvnPath: false, divergOk: false, divergLabel: '', approachOk: true,
      approachReason: 'Нейтральный подход', signal: 'SHORT', rsiNow: 50, corr: { btc_corr: 0.5, eth_corr: 0.5 }, testCount: 3,
      isDeadSession: false, session: '🇺🇸 Нью-Йорк сессия', rrScore: 2.0, memcoin: false,
    };
    const q = L.accumulateQuality(minimal);   // 0 + 1 (class 3) − 1 (counter) − 1 (test #3) = −1 → clamp 0
    expect(q.quality).toBe(0);
    expect(q.reasons).toEqual(['✅ Пробой уровня', '⚠️ [BOUNCE_PLAIN] — паттерн класса D', '✅ Уровень класса 3 (Рабочий)', '⚠️ Контртренд', '⚠️ Тест #3 — уровень слабеет']);
    expect(L.accumulateQuality({ ...minimal, instPattern: '', isCounter: false, testCount: 2 }).reasons).toEqual(['✅ Пробой уровня', '✅ Уровень класса 3 (Рабочий)', '✅ По локальному тренду', '✅ Тест #2 уровня (оптимально)']);
    expect(L.accumulateQuality({ ...minimal, patternBonus: 2, instPattern: 'FAKEOUT_PINBAR' }).quality).toBe(1);
    expect(L.accumulateQuality({ ...minimal, patternBonus: 1, instPattern: 'SFP', sClass: 2 }).quality).toBe(0);   // 1+1−1−1
    expect(L.accumulateQuality({ ...minimal, isCounter: false, sClass: 2 }).quality).toBe(1);                       // 1+1−1
    expect(L.accumulateQuality({ ...minimal, approachReason: 'Недостаточно данных' }).reasons).not.toContain('✅ Недостаточно данных');
    expect(L.accumulateQuality({ ...minimal, approachReason: '✅ Затухающий импульс' }).quality).toBe(0);        // −1 +1 → 0
    expect(L.accumulateQuality({ ...minimal, isCounter: false, approachReason: '✅ Консолидация у уровня' }).quality).toBe(3);   // 1+1+1+1−1
    expect(L.accumulateQuality({ ...minimal, rsiNow: 60 }).reasons).toContain('✅ RSI выходит из перекупленности');
    expect(L.accumulateQuality({ ...minimal, rsiNow: 70 }).reasons).not.toContain('✅ RSI выходит из перекупленности');
    expect(L.accumulateQuality({ ...minimal, signal: 'LONG', rsiNow: 30 }).reasons).not.toContain('✅ RSI выходит из перепроданности');
    expect(L.accumulateQuality({ ...minimal, volRatio: 1.0 }).reasons).toContain('✅ Объём x1.0');
    expect(L.accumulateQuality({ ...minimal, corr: { btc_corr: NaN, eth_corr: 0.1 } }).reasons).not.toContain('✅ Независимое движение (corr < 0.4)');
    const drop = L.accumulateQuality({ ...minimal, rrScore: 1.19 });
    expect(drop.reject).toBe('rr');
    expect(drop.reasons[drop.reasons.length - 1]).toBe('⚠️ Тест #3 — уровень слабеет');   // nothing after the dead-session step
    expect(L.accumulateQuality({ ...minimal, rrScore: 1.2 }).reasons.pop()).toBe('⚠️ Взвешенный R:R: 1.20 (ниже 1.8)');
    expect(L.accumulateQuality({ ...minimal, rrScore: 1.8 }).reasons.pop()).toBe('⚠️ Тест #3 — уровень слабеет');
    expect(L.accumulateQuality({ ...minimal, sZone: { mtf_label: 'Институциональный', has_hvn: false }, isCounter: false }).reasons).toContain('✅ Институциональный MTF уровень (3 ТФ)');
    expect(L.accumulateQuality({ ...minimal, sZone: { timeframes: ['a', 'b', 'c'], has_hvn: false } }).quality).toBe(1);   // +2
    expect(L.accumulateQuality({ ...minimal, memcoin: true, isCounter: false, patternBonus: 3, instPattern: 'X', sClass: 1, divergOk: true, divergLabel: 'd', hasLvnPath: true, sZone: { has_hvn: true }, testCount: 1 }).quality).toBe(5);
  });
  it('final checklist', () => {
    const ok = { approachOk: true, hasPattern: false, sType: 'Пробой уровня', volRatio: 1.6, rrActual: 2.0, effectiveMinRr: 2.0, testCount: 3, maxLevelTests: 4 };
    expect(L.finalChecklist(ok).ok).toBe(true);
    expect(L.finalChecklist({ ...ok, volRatio: 1.2 }).ok).toBe(false);                         // no pattern, not a fakeout, vol ≤ 1.2
    expect(L.finalChecklist({ ...ok, volRatio: 1.2, sType: 'SFP (Захват ликвидности)' }).ok).toBe(true);
    expect(L.finalChecklist({ ...ok, volRatio: 1.2, sType: 'Ложный пробой (Fakeout)' }).ok).toBe(true);
    expect(L.finalChecklist({ ...ok, volRatio: 1.2, hasPattern: true }).ok).toBe(true);
    expect(L.finalChecklist({ ...ok, rrActual: 1.99 }).items).toEqual([true, true, true, false, true]);
    expect(L.finalChecklist({ ...ok, testCount: 4 }).items[4]).toBe(false);
    expect(L.finalChecklist({ ...ok, approachOk: false }).items[1]).toBe(false);
  });
});

describe('levels_filters.evaluate modes, cooldown state, indicator wrapper, post-steps, explanation, result', () => {
  const frames = loadFrames('SYNRG04-USDT-SWAP');
  const df = frames['1h'];
  it('evaluate: off → not evaluated, shadow → listed, enforce → first triggered name; vol / confirm rules', () => {
    const trending = loadFrame('SYNUP01-USDT-SWAP', '1h');
    expect(L.regimeTriggersSkip(trending, '1h')).toBe(true);
    expect(L.evaluate(trending, 'LONG', 1, 1, 1, { regimeMode: 'off' })).toEqual([null, []]);
    expect(L.evaluate(trending, 'LONG', 1, 1, 1, { regimeMode: 'shadow' })).toEqual([null, ['regime']]);
    expect(L.evaluate(trending, 'LONG', 1, 1, 1, { regimeMode: 'enforce', tf: '1h' })).toEqual(['regime', []]);
    expect(L.evaluate(trending, 'LONG', 1, 100, 3, { regimeMode: 'shadow', volMode: 'enforce', volMaxAtrPct: 2.5 })).toEqual(['vol', ['regime']]);
    expect(L.evaluate(trending, 'LONG', 1, 100, 2.5, { volMode: 'enforce', volMaxAtrPct: 2.5 })).toEqual([null, []]);
    expect(L.volTriggersSkip(3, 100, 2.5)).toBe(true);
    expect(L.volTriggersSkip(3, 0, 2.5)).toBe(false);
    expect(L.volTriggersSkip('x', 100, 2.5)).toBe(false);
    const bar = Frame.fromBars([[0, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1], [2, 100, 101, 98, 100.5, 1]]);
    expect(L.confirmTriggersSkip(bar, 'LONG', 99)).toBe(false);          // low ≤ 99 and close > 99 → confirmed
    expect(L.confirmTriggersSkip(bar, 'LONG', 97)).toBe(true);           // never touched
    expect(L.confirmTriggersSkip(bar, 'SHORT', 100.8)).toBe(false);
    expect(L.confirmTriggersSkip(bar, 'SHORT', 100.2)).toBe(true);       // close above the level
    expect(L.confirmTriggersSkip(bar, 'X', 99)).toBe(false);
    expect(L.confirmTriggersSkip(bar.slice(0, 2), 'LONG', 99)).toBe(false);
    expect(L.gatesActive({ LEVELS_REGIME_GATE: 'off', LEVELS_VOL_GATE: 'off', LEVELS_ENTRY_CONFIRM: 'off' })).toBe(false);
    expect(L.gatesActive(L.LEVELS_ENV)).toBe(true);
    expect(L.MODES).toEqual(['off', 'shadow', 'enforce']);
  });
  it('CooldownState: bars since the marked bar, 1_000_000 when unknown, oldest evicted above the cap', () => {
    const cd = new L.CooldownState({ max: 2 });
    expect(cd.barsSinceSignal('A', df.prefix(210))).toBe(1_000_000);
    cd.markSignal('A', df.prefix(210));
    expect(cd.barsSinceSignal('A', df.prefix(210))).toBe(0);
    expect(cd.barsSinceSignal('A', df.prefix(214))).toBe(4);
    expect(cd.barsSinceSignal('A', df.prefix(0))).toBe(1_000_000);   // fewer than 2 bars
    cd.markSignal('B', df.prefix(220));
    cd.markSignal('C', df.prefix(230));
    expect([...cd.map.keys()]).toEqual(['B', 'C']);
  });
  it('createIndicator: cooldown gate, reject counters per instance, HTF zone cache reuse', () => {
    const cfg = cfgOf('default');
    const ind = L.createIndicator(cfg);
    const b = barInputs(frames, 300);
    const r1 = ind.analyze('SYNRG04-USDT-SWAP', b.df, null, b.dfBtc, b.dfEth);
    expect(r1.rejectReason === null || typeof r1.rejectReason === 'string').toBe(true);
    ind.markSignal('SYNRG04-USDT-SWAP', b.df);
    const r2 = ind.analyze('SYNRG04-USDT-SWAP', barInputs(frames, 302).df, null, null, null);
    expect([r2.signal, r2.rejectReason, r2.stage]).toEqual([null, 'none', 'cooldown']);
    expect(ind.analyze('SYNRG04-USDT-SWAP', barInputs(frames, 305).df, null, null, null).stage).not.toBe('cooldown');
    expect(ind.analyze('X', df.prefix(150), null, null, null).stage).toBe('too_short');
    const stats = ind.getAnalyzeStats();
    expect(Object.values(stats).reduce((a, x) => a + x, 0)).toBeGreaterThanOrEqual(1);
    ind.resetAnalyzeStats();
    expect(ind.getAnalyzeStats()).toEqual({});
    expect(L.analyzeOnDemand('X', df.prefix(48), null, null, null, cfg).stage).toBe('too_short');   // 49 bars < 50
  });
  it('scannerPostSteps: squeeze boost (+1, cap 10) and the min-quality gate, relaxed lowering', () => {
    const lv = loadExpected('levels');
    const s = lv.fixtures['SYNLV02-USDT-SWAP'].default.signals[0];
    const b = barInputs(loadFrames('SYNLV02-USDT-SWAP'), s.i);
    const post = L.scannerPostSteps({ quality: s.quality }, b.df, 3);
    expect(post).toEqual({ squeeze_score: s.squeeze_score, quality_after_squeeze: s.quality_after_squeeze, passes_min_quality: s.passes_min_quality });
    expect(L.scannerPostSteps({ quality: 10 }, b.df, 3).quality_after_squeeze).toBe(10);
    expect(L.scannerPostSteps({ quality: 4 }, b.df, 6).passes_min_quality).toBe(false);
    expect(L.scannerPostSteps({ quality: 4 }, b.df, 6, { relaxed: true }).passes_min_quality).toBe(true);   // 5 ≥ max(2, 5)
  });
  it('human explanation branches and the SFP-SHORT name quirk; SignalResult field order', () => {
    const t = (sType, sig = 'LONG', hits = 2) => L.buildHumanExplanation(sig, 1.2345, 2, hits, sType, 1.2, 1.18, 1.3, 1.4, 5.0, 10.0, 1.6667, '🇺🇸 Нью-Йорк сессия', '🔗 Ходит за BTC', '');
    expect(t('Отскок от поддержки')).toBe('Сильный уровень 1.2345 (2 касания). Цена подошла к уровню поддержки и показывает признаки разворота. Отскок от ключевой зоны. 🇺🇸 Нью-Йорк сессия 🔗 Ходит за BTC Стоп за структуру 1.18 (риск 1.7%). TP1: 1.3 (R:R 1:5.0), TP2: 1.4 (R:R 1:10.0).');
    expect(t('SFP (Ложный пробой вверх)', 'SHORT')).toContain('Цена пробила уровень вверх, но не закрепилась');   // "Ложный пробой" wins over "SFP"
    expect(t('SFP (Захват ликвидности)')).toContain('Захват ликвидности снизу (SFP)');
    expect(t('Ложный пробой (Fakeout)')).toContain('ложный пробой вниз, ловушка для продавцов');
    expect(t('Ретест пробитого уровня')).toContain('бывшее сопротивление стало поддержкой');
    expect(t('Ретест пробитой поддержки', 'SHORT')).toContain('бывшая поддержка стала сопротивлением');
    expect(t('Пробой уровня')).toContain('Пробой ключевого уровня вверх');
    expect(t('Пробой поддержки', 'SHORT')).toContain('Пробой ключевой поддержки вниз');
    expect(t('Отскок от сопротивления', 'SHORT')).toContain('теряет импульс');
    expect(t('x', 'LONG', 3)).toContain('(3 касания) — каждый раз давал уверенную реакцию.');
    expect(t('x', 'LONG', 5)).toContain('(5 касаний) — каждый раз');
    expect(L.buildHumanExplanation('LONG', 1, 9, 1, 'x', 1, 1, 1, 1, 1, 1, 1, '', '', '✅ Бычья дивергенция RSI')).toBe('Рабочий уровень 1 (1 касания). Цена подошла к уровню поддержки и показывает признаки разворота. Отскок от ключевой зоны. ✅ Бычья дивергенция RSI Стоп за структуру 1 (риск 1.0%). TP1: 1 (R:R 1:1.0), TP2: 1 (R:R 1:1.0).');
    const sr = L.signalResult({ symbol: 'S', direction: 'LONG', entry: 1, sl: 0.9, tp1: 1.1, tp2: 1.2, tp3: 1.3, risk_pct: 10, quality: 5 });
    expect(Object.keys(sr)).toEqual(['symbol', 'direction', 'entry', 'sl', 'tp1', 'tp2', 'tp3', 'risk_pct', 'quality', 'reasons', 'rsi', 'volume_ratio', 'trend_local', 'trend_htf', 'pattern', 'breakout_type', 'is_counter_trend', 'human_explanation', 'level_class', 'test_count', 'rr_score', 'corr_label', 'session', 'btc_corr', 'eth_corr', 'tp1_close_pct', 'tp2_close_pct', 'tp3_close_pct', 'move_sl_to_be_after_tp1']);
    expect([sr.reasons, sr.rsi, sr.level_class, sr.tp1_close_pct, sr.move_sl_to_be_after_tp1]).toEqual([[], 50.0, 3, 0.4, true]);
    expect(() => L.signalResult({ symbol: 'S', bogus: 1 })).toThrow(/unexpected field/);
    expect(r10(L.calculateRrScore('LONG', 100, 99, 102, 103, 104.5))).toBe(2.8);
  });
});
