/**
 * pyUnicode — the Unicode database of the bot's interpreter (CPython 3.11, unicodedata 14.0.0)
 * and the str semantics built on it, for every port of a Python builtin whose result depends on
 * it: int() / float() of non-ASCII digits and spaces, re `\d` `\s` `\w` `\b`, str.isspace() /
 * strip() / split(), str.isdigit() / isupper() / isprintable() / repr(), str.lower() / upper() /
 * capitalize().
 *
 * Node ships its own, newer Unicode (Node 22: 16.0), and CPython 3.12 ships 15.0.0 — neither is
 * the bot's. Characters assigned after 14.0.0 are unassigned (Cn) for the bot: not printable
 * (repr() escapes them), never a digit or a letter (Kawi U+11F50 and Nag Mundari U+1E4F0 digits,
 * new in 15.0, make int() raise), and without a case mapping (Node upper-cases U+0264 ɤ to the
 * Unicode 16 letter U+A7CB; CPython 3.11 keeps it). The tables are generated by
 * tests/challenge/gen/gen_unicode_tables.py --write with the production interpreter.
 */

'use strict';

// BEGIN unicode tables
// unicodedata 14.0.0 (CPython 3.11.17)
const ND_ZEROS = [0x30, 0x660, 0x6f0, 0x7c0, 0x966, 0x9e6, 0xa66, 0xae6, 0xb66, 0xbe6, 0xc66, 0xce6, 0xd66, 0xde6, 0xe50, 0xed0, 0xf20, 0x1040, 0x1090, 0x17e0, 0x1810, 0x1946, 0x19d0, 0x1a80, 0x1a90, 0x1b50, 0x1bb0, 0x1c40, 0x1c50, 0xa620, 0xa8d0, 0xa900, 0xa9d0, 0xa9f0, 0xaa50, 0xabf0, 0xff10, 0x104a0, 0x10d30, 0x11066, 0x110f0, 0x11136, 0x111d0, 0x112f0, 0x11450, 0x114d0, 0x11650, 0x116c0, 0x11730, 0x118e0, 0x11950, 0x11c50, 0x11d50, 0x11da0, 0x16a60, 0x16ac0, 0x16b50, 0x1d7ce, 0x1d7d8, 0x1d7e2, 0x1d7ec, 0x1d7f6, 0x1e140, 0x1e2f0, 0x1e950, 0x1fbf0];
const PY_SPACE_HI = [0x85, 0xa0, 0x1680, 0x2000, 0x2001, 0x2002, 0x2003, 0x2004, 0x2005, 0x2006, 0x2007, 0x2008, 0x2009, 0x200a, 0x2028, 0x2029, 0x202f, 0x205f, 0x3000];
const NONPRINT = '3k.w,d.0,jv.1,7.3,8.0,2.0,l.0,b2.0,13.1,1f.1,4.0,1k.7,s.3,7.g,n.0,5d.0,1d.1,1o.1,2u.d,1o.1,1e.1,g.0,t.1,2.0,c.4,w.8,23.0,4i.0,9.1,3.1,n.0,8.0,2.2,5.1,a.1,3.1,5.7,2.3,3.0,6.1,q.1,4.0,7.3,3.1,n.0,8.0,3.0,3.0,3.1,2.0,6.3,3.1,4.2,2.6,5.0,2.6,i.9,4.0,a.0,4.0,n.0,8.0,3.0,6.1,b.0,4.0,4.1,2.e,5.1,d.6,8.0,4.0,9.1,3.1,n.0,8.0,3.0,6.1,a.1,3.1,4.6,4.3,3.0,6.1,j.9,3.0,7.2,4.0,5.2,3.0,2.0,3.2,3.2,4.2,d.3,6.2,4.0,5.1,2.5,2.d,m.4,e.0,4.0,o.0,h.1,a.0,4.0,5.6,3.0,4.1,2.1,5.1,b.6,n.0,4.0,o.0,b.0,6.1,a.0,4.0,5.6,3.5,3.0,5.1,b.0,3.c,e.0,4.0,1g.0,4.0,7.3,h.1,r.0,4.0,j.2,p.0,a.0,2.1,8.2,2.3,7.0,2.0,9.5,b.1,4.b,1n.3,u.10,3.0,2.0,6.0,p.0,2.0,o.1,6.0,2.0,7.1,b.1,5.v,21.0,11.3,14.0,11.0,g.0,e.10,5j.0,2.4,2.1,ai.0,5.1,8.0,2.0,5.1,16.0,5.1,y.0,5.1,8.0,2.0,5.1,g.0,1m.0,5.1,1w.1,x.2,r.5,2f.1,7.1,ht.0,t.2,2i.6,n.8,p.8,l.b,e.0,4.0,3.b,2n.1,b.5,b.5,f.0,c.5,2i.6,18.4,1z.9,w.0,d.3,d.3,2.2,17.1,6.a,19.3,r.5,c.2,1r.1,1u.0,u.1,c.5,b.5,f.1,w.1c,26.2,1c.0,39.7,1p.2,g.2,1p.6,18.1,c.7,18.4,ev.1,7.1,13.1,7.1,9.0,2.0,2.0,2.0,w.1,1i.0,g.0,f.1,7.0,k.1,4.0,a.g,p.7,1c.g,3.1,s.0,e.2,y.e,y.e,3x.3,ig.o,c.k,1ed.1,x.0,9q.4,1a.0,2.4,2.1,1l.6,3.d,p.8,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,3j.x,r.0,2i.b,5z.p,d.4,1s.0,2f.1,2w.4,18.0,2n.0,2d.b,1c.0,mlq.2,1k.8,9p.j,55.7,5o.4,3.0,2.0,6.n,1o.2,b.5,1l.7,1z.7,d.5,39.a,v.2,27.0,c.3,y.0,1k.8,f.1,b.1,2w.n,t.9,7.1,7.1,7.8,8.0,8.0,1p.3,3j.1,b.5,8md.b,o.3,1e.6ir,a7.1,2z.11,8.b,6.4,r.0,6.0,2.0,3.0,3.0,3i.f,ce.1,1j.6,2.v,17.5,1g.0,k.0,5.3,6.0,3s.3,5b.2,7.1,7.1,7.1,4.2,8.0,8.c,3.1,d.0,r.0,k.0,3.0,g.1,f.x,3g.4,4.3,1a.2,2h.0,e.2,2.1a,1b.3l,u.2,1e.e,t.3,11.8,v.4,18.4,v.0,12.3,f.15,4f.1,b.5,11.3,11.3,15.7,1h.a,d.0,g.0,8.0,3.0,c.0,g.0,8.0,3.1u,8o.8,n.9,9.n,7.0,17.0,a.1w,7.1,2.0,19.0,3.2,2.1,o.0,21.7,a.1b,k.0,3.4,y.2,s.4,2.1r,1l.3,l.1,1f.0,3.4,9.0,4.0,u.1,4.3,b.6,a.6,1t.v,14.3,d.8,1j.2,u.1,s.4,r.6,5.b,8.27,22.1i,1g.c,1g.6,1b.7,b.85,w.0,17.0,4.1,3.25,15.7,17.l,r.11,t.j,o.8,27.3,11.8,1r.0,6.c,q.6,b.5,1i.0,j.7,14.8,2p.0,l.a,j.0,19.1s,8.0,2.0,5.0,g.0,c.5,1o.4,b.5,5.0,9.1,3.1,n.0,8.0,3.0,6.0,b.1,3.1,4.1,2.5,2.4,8.1,8.2,6.3u,2l.0,6.t,21.7,b.4l,1j.1,13.x,1y.a,b.5,e.i,1n.5,b.1h,s.1,g.3,o.54,1p.2r,2c.b,9.1,2.1,9.0,3.0,v.0,3.1,d.8,b.1x,9.1,1b.1,c.q,21.7,2c.c,22.7a,a.0,1a.0,f.9,u.2,x.1,n.0,f.20,8.0,3.0,19.2,2.0,3.0,a.7,b.5,7.0,3.0,12.0,3.0,7.6,b.8l,q.52,2.e,1f.c,po.2t,34.0,6.a,5h.217,2s.c,ts.34g,g8.6ns,fu.6,w.0,b.3,2a.0,b.5,v.1,7.9,1z.9,b.0,8.0,m.4,k.j3,2k.2s,24.3,1m.6,i.1r,6.a,3.d,4qh.7,yf.15,a.6w6,5.0,8.0,3.0,84.18,4.g,5.7,b1.1s3,30.4,e.2,a.6,b.1,5.3mn,1b.1,o.8,39.1n,6v.9,14.1,23.7,35.k,1z.49,l.b,2g.8,q.3q,2e.0,20.0,3.1,2.1,3.1,5.0,d.0,2.0,8.0,1u.0,5.1,9.0,8.0,t.0,5.0,6.0,2.2,8.0,9h.1,85.1,jj.e,6.0,g.un,w.68,8.0,i.1,8.0,3.0,6.5w,1a.2,f.1,b.3,3.8v,w.g,1n.4,2.yn,8.0,5.0,3.0,g.0,5i.1,h.14,25.3,b.3,3.ls,1x.23,1q.5d,5.0,s.0,3.0,2.1,2.0,b.0,5.0,2.0,2.5,2.3,2.0,2.0,2.0,4.0,3.0,2.1,2.0,2.0,2.0,2.0,2.0,3.0,2.1,5.0,8.0,5.0,5.0,2.0,b.0,i.4,4.0,6.0,i.1f,3.7h,19.3,2t.b,g.1,g.0,g.0,12.9,4v.1j,u.c,19.3,a.6,3.d,7.49,rd.4,h.2,e.2,39.b,2i.6,d.3,2.e,d.3,1l.7,b.5,15.7,v.1,3.25,9h.b,f.1,6.2,6.2,8.8,u.2,c.4,7.9,b.5,9.7,8.8,44.0,1k.10,b.sl,wyp.v,37e.6,67.1,4g3.d,5rm.2e6,f3.15t,3t8.fcms,6p.47bj';
const DIGIT = '1c.9,3d.1,6.0,147.9,3r.9,5j.9,bh.9,3b.9,3b.9,3b.9,3b.9,3b.9,3b.9,3b.9,3b.9,3b.9,2p.9,3b.9,1z.9,7r.9,1z.9,k0.8,vj.9,13.9,8d.9,3l.a,4m.9,7.9,53.9,2f.9,3r.9,7.9,t3.0,4.5,7.9,rb.8,c.8,c.8,2i.0,b.8,2.0,hj.8,2.8,2.8,ozy.9,iv.9,13.9,5j.9,n.9,2f.9,bb.9,gev.9,13b.9,13r.3,kt.9,87.8,dm.8,c.9,3l.9,1p.9,41.9,7r.9,9j.9,3b.9,af.9,2v.9,2v.9,br.9,2v.9,l3.9,6v.9,1z.9,f5j.9,2f.9,3r.9,lf9.1d,1tt.9,br.9,193.9,1if.a,25i.9';
const ALNUM = '1c.9,8.p,7.p,1c.0,8.1,2.0,4.1,2.2,2.m,2.u,2.cp,5.b,f.4,8.0,2.0,3m.4,2.1,3.3,2.0,7.0,2.2,2.0,2.j,2.2a,2.3u,9.4l,2.11,3.0,7.14,20.q,5.3,1a.16,m.9,5.1,2.2q,2.0,g.1,8.e,3.0,h.0,2.t,u.2g,c.0,f.16,a.1,5.0,6.l,5.0,a.0,4.0,o.o,8.a,6.n,2.5,i.15,1n.1h,4.0,j.0,8.9,5.9,2.f,5.7,3.1,3.l,2.6,2.0,4.3,4.0,h.0,e.1,2.2,5.b,3.5,3.0,9.5,5.1,3.l,2.6,2.1,2.1,2.1,w.3,2.0,8.9,3.2,h.8,2.2,2.l,2.6,2.1,2.4,4.0,j.0,g.1,5.9,a.0,c.7,3.1,3.l,2.6,2.1,2.4,4.0,v.1,2.2,5.9,2.6,c.0,2.5,4.2,2.3,4.1,2.0,2.1,4.1,4.2,4.b,n.0,m.c,j.7,2.2,2.m,2.f,4.0,r.2,3.0,3.1,5.9,9.6,2.0,5.7,2.2,2.m,2.9,2.4,4.0,w.1,2.1,5.9,2.1,i.8,2.2,2.14,3.0,h.0,6.2,2.9,5.i,2.5,6.h,4.n,2.8,2.0,3.6,w.9,i.1b,2.1,d.6,a.9,14.1,2.0,2.4,2.n,2.0,2.9,2.1,a.0,3.4,2.0,a.9,3.3,x.0,w.j,d.7,2.z,s.4,38.16,l.a,7.5,5.3,4.0,4.1,8.2,5.c,d.0,2.9,7.11,2.0,6.0,3.16,2.98,2.3,3.6,2.0,2.3,3.14,2.3,3.w,2.3,3.6,2.0,2.3,3.e,2.1k,2.3,3.1u,f.j,4.f,h.2d,3.5,4.h7,3.g,2.p,6.22,4.a,8.h,e.i,f.h,f.c,2.2,g.1f,10.0,5.0,4.9,7.9,n.9,7.2g,8.4,3.x,2.0,6.1x,b.u,14.13,3.4,c.17,5.p,7.a,12.m,a.1g,18.9,7.9,e.0,2m.1a,i.7,4.9,16.t,e.1j,r.z,t.9,4.1c,3.8,8.16,3.2,16.3,2.5,2.1,4.0,6.5b,1t.7p,3.5,3.11,3.5,3.7,2.0,2.0,2.0,2.u,3.1g,2.6,2.0,4.2,2.6,4.3,3.5,5.c,6.2,2.6,38.1,3.5,6.a,7.c,2u.0,5.0,3.9,2.0,4.4,7.0,2.0,2.0,2.3,2.a,3.3,6.4,5.0,2.1l,k7.1n,27.l,hj.t,vh.6c,7.3,4.1,a.0,3.11,2.0,6.0,3.1j,8.0,h.m,a.6,2.6,2.6,2.6,2.6,2.6,2.6,2.6,29.0,d2.2,q.8,8.4,3.4,5.2d,7.2,2.2h,2.3,6.16,2.2l,4.3,b.v,1d.f,x.9,v.7,2.e,x.9,14.e,8x.533,1t.h3g,1w.19,3.7g,4.r,l.1a,h.u,3.27,14.8,3.2u,3.1r,6.1,2.0,2.4,p.f,2.2,2.3,2.m,e.5,b.1f,f.1d,t.9,p.5,4.0,2.1,2.11,b.m,q.s,8.1a,t.a,7.4,2.o,2.14,o.2,2.7,5.9,7.m,4.0,4.1d,2.0,4.1,3.4,3.0,2.0,p.2,3.a,8.2,d.5,3.5,3.5,a.6,2.6,2.16,2.d,7.36,e.9,7.8mb,d.m,5.1c,6it.a5,3.2x,13.6,d.4,6.0,2.9,2.c,2.4,2.0,2.1,2.1,2.2z,y.a2,j.1r,3.1h,15.b,39.4,2.3q,k.9,8.p,7.p,c.2g,4.5,3.5,3.5,3.2,10.b,2.p,2.i,2.1,2.e,3.d,z.3e,d.18,d.1k,i.1,6t.s,4.1c,h.q,5.z,a.t,6.11,b.t,3.z,5.7,2.4,17.4d,3.9,7.z,5.z,5.13,9.1f,d.a,2.e,2.6,2.1,2.a,2.e,2.6,2.1,1w.8m,a.l,b.7,p.5,2.15,2.8,1y.5,3.0,2.17,2.1,4.0,3.m,3.u,3.11,9.8,1d.i,2.1,6.w,5.p,1z.1j,5.j,3.1a,g.3,2.2,2.s,b.8,o.u,2.v,x.7,2.r,7.4,h.1h,b.l,3.q,6.p,o.6,29.20,1k.1e,e.1e,8.15,d.9,87.u,2.15,7.1,27.13,9.l,c.3,s.h,1b.r,l.m,d.1g,r.t,2.1,3.0,e.18,x.o,8.9,a.z,g.9,5.0,3.0,9.y,4.0,d.1b,f.3,c.a,2.0,5.j,c.h,2.o,2d.6,2.0,2.3,2.e,2.9,8.1a,i.9,c.7,3.1,3.l,2.6,2.1,2.4,4.0,j.0,d.4,4f.1g,j.3,6.9,6.2,v.1b,l.1,2.0,9.9,4n.1a,16.3,11.1b,l.0,c.9,13.16,e.0,8.9,1j.q,m.b,5.6,56.17,39.2a,d.7,3.0,3.7,2.1,2.n,g.0,2.0,f.9,1z.7,3.12,h.0,2.0,t.0,b.13,8.0,m.0,c.19,k.0,j.20,7c.8,2.10,i.0,g.s,6.t,35.6,2.1,2.11,m.0,a.9,7.5,2.1,2.v,f.0,8.9,8n.i,5a.0,g.k,18.pl,2v.32,i.5f,219.2o,g.tq,34i.g6,6nu.fs,8.u,2.9,7.26,2.9,7.t,j.1b,h.3,d.9,2.6,2.k,6.i,j5.2e,2y.22,6.0,1v.c,1t.1,2.0,t.4qf,9.yd,17.8,6w8.3,2.6,2.1,2.82,1a.2,i.3,9.az,1s5.2y,6.c,4.8,8.9,4ef.j,31.o,3s.2c,2.1y,2.1,3.0,3.1,3.3,2.b,2.0,2.6,2.1s,2.3,3.7,2.6,2.r,2.3,2.4,2.0,4.6,2.9f,3.o,2.o,2.u,2.o,2.u,2.o,2.u,2.o,2.u,2.o,2.7,3.1d,1dt.u,de.18,b.6,3.9,5.0,8y.t,j.17,5.9,yv.6,2.3,2.1,2.e,2.5g,3.8,1d.1v,8.0,5.9,m0.1m,2.2,2.3,25.18,2.e,5f.3,2.q,2.1,2.0,3.0,2.9,2.3,2.0,2.0,7.0,5.0,2.0,2.0,2.2,2.1,2.0,3.0,2.0,2.0,2.0,2.0,2.1,2.0,3.3,2.6,2.3,2.3,2.0,2.9,2.g,6.2,2.4,2.g,g5.c,25g.9,sn.wyn,x.37c,8.65,3.4g1,f.5rk,2e8.f1,15v.3t6';
const UPPER = '1t.p,2u.m,2.6,y.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,3.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,3.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.1,2.0,2.0,4.1,2.0,2.1,2.2,3.3,2.1,2.2,4.1,2.1,2.0,2.0,2.1,2.0,3.0,2.1,2.2,2.0,2.1,4.0,8.0,3.0,3.0,3.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,3.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,3.0,3.0,2.2,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,8.1,2.1,3.0,2.3,2.0,2.0,2.0,2.0,82.0,2.0,4.0,9.0,7.0,2.2,2.0,2.1,2.g,2.8,10.0,3.2,4.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,6.0,3.0,2.1,3.1e,1d.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,a.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.1,2.0,2.0,2.0,2.0,2.0,2.0,3.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,3.11,28a.11,2.0,6.0,k3.2d,1p7.16,3.2,8x.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,a.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,a.7,9.5,b.7,9.7,9.5,c.0,2.0,2.0,2.0,9.7,21.3,d.3,d.3,d.4,c.3,7b.0,5.0,4.2,3.2,3.0,4.4,7.0,2.0,2.0,2.3,3.3,b.1,6.0,r.f,k.0,mr.p,1f5.1b,1d.0,2.2,3.0,2.0,2.0,2.3,2.0,3.0,9.2,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,9.0,2.0,5.0,nym.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,k.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,3s.0,2.0,2.0,2.0,2.0,2.0,2.0,4.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,b.0,2.0,2.1,2.0,2.0,2.0,2.0,5.0,2.0,3.0,2.0,4.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.4,2.4,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.3,2.0,7.0,6.0,2.0,t.0,h7w.p,xy.13,3t.z,4d.a,2.e,2.6,2.1,1d7.1e,2cu.v,gw1.v,k2p.p,r.p,r.p,r.0,2.1,3.0,3.1,3.3,2.7,r.p,r.1,2.3,3.7,2.6,s.1,2.3,2.4,2.0,4.6,s.p,r.p,r.p,r.p,r.p,r.p,v.o,y.o,y.o,y.o,y.o,y.0,3ee.x,1lb.p,7.p,7.p';
const LOWER = '2p.p,1c.0,b.0,5.0,11.n,2.7,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.1,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.1,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,3.0,2.0,2.2,3.0,2.0,3.0,4.1,5.0,3.0,4.2,3.0,3.0,2.0,2.0,3.0,2.1,2.0,3.0,4.0,2.0,3.1,3.2,7.0,3.0,3.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.1,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.1,3.0,2.0,4.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.6,3.0,3.1,2.0,5.0,2.0,2.0,2.0,2.1w,2.z,8.1,v.4,2p.0,18.0,2.0,4.0,3.3,j.0,s.y,2.1,4.2,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.4,2.0,3.0,3.1,1g.1b,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,a.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,3.0,2.0,2.0,2.0,2.0,2.0,2.1,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1d.14,288.16,3.2,l5.5,1oj.8,3c.5b,1u.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.8,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.8,9.5,b.7,9.7,9.5,b.7,9.7,9.d,3.7,9.7,9.7,9.4,2.1,7.0,4.2,2.1,9.3,3.1,9.7,b.2,2.1,3e.0,e.0,h.c,32.0,4.1,4.0,s.0,5.0,5.0,3.1,9.3,5.0,y.f,5.0,ng.p,1fr.1b,2.0,4.1,2.0,2.0,2.0,5.0,2.1,2.7,4.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.1,8.0,2.0,5.0,d.11,2.0,6.0,nx0.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,k.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.2,3q.0,2.0,2.0,2.0,2.0,2.0,2.2,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.9,2.0,2.0,3.0,2.0,2.0,2.0,2.0,5.0,2.0,3.0,2.2,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,6.0,6.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,5.0,2.0,7.0,2.0,2.0,2.0,2.0,t.0,2.2,mu.16,2.c,8.27,fnl.6,d.4,tm.p,y6.13,3t.z,4c.a,2.e,2.6,2.1,ck.0,3.2,2.15,2.8,zq.1e,2by.v,gw1.v,k2j.p,r.6,2.h,r.p,r.3,2.0,2.6,2.a,r.p,r.p,r.p,r.p,r.p,r.p,r.p,r.p,r.r,t.o,2.5,r.o,2.5,r.o,2.5,r.o,2.5,r.o,2.5,2.0,1f9.9,2.j,1z8.x';
const TITLE = 'cl.0,3.0,3.0,13.0,5ue.7,9.7,9.7,d.0,g.0,1c.0';
const CASE_IGNORABLE = '13.0,7.0,c.0,10.0,2.0,20.0,5.0,2.0,5.0,3.1,e0.5b,5.1,5.0,a.1,2.0,70.6,5s.0,6.0,1e.18,2.0,2.1,2.1,2.0,19.0,c.5,b.a,2.0,10.0,b.k,h.0,2u.7,2.9,2.3,y.0,2.0,v.q,2k.a,1n.a,5.0,3.0,p.n,18.2,19.0,8.1,7.7,16.1l,1k.0,2.0,5.7,5.0,4.6,b.1,e.0,g.0,1n.0,5.3,9.0,l.1,r.0,3.1,1m.0,5.1,5.1,3.2,4.0,v.1,4.0,c.1,1m.0,5.4,2.1,5.0,l.1,n.5,2.0,1n.0,3.0,2.3,9.0,8.1,c.1,v.0,1q.0,d.0,1f.0,4.0,1k.0,2.2,6.2,2.3,8.1,c.1,u.0,1n.0,3.0,7.0,6.1,l.1,t.1,1m.1,5.3,9.0,l.1,u.0,21.0,8.2,2.0,2j.0,3.6,c.8,2r.0,3.8,a.0,2.5,23.1,s.0,2.0,2.0,1k.d,2.4,2.1,6.a,2.z,a.0,2v.3,2.5,2.1,3.1,q.1,5.2,h.3,e.0,3.1,7.0,g.0,2n.0,gx.2,qb.2,u.1,v.1,v.1,1t.1,2.6,9.0,3.a,4.0,6.0,1a.4,1g.0,1u.1,z.0,3b.2,5.1,a.0,7.2,64.1,3.0,1n.0,2.6,2.0,2.0,3.7,7.9,3.0,14.0,9.u,1e.3,1d.0,2.4,2.0,6.0,15.8,d.1,x.3,3.1,2.2,1l.0,2.1,4.0,2.2,1n.7,3.1,1t.5,2b.2,2.c,2.6,5.0,7.0,4.1,1f.1q,e.0,z.2s,ce.0,2.2,c.2,e.2,e.2,e.1,d.4,9.1,b.0,3.0,3.4,1e.4,2.9,2.0,e.0,h.c,1g.w,2a4.1,36.2,3i.0,g.0,2p.v,1c.0,d2.0,11.3,4.4,6.0,2m.5,2m.2,lxz.0,yr.5,7j.0,2r.3,2.9,2.0,t.3,29.1,f.x,27.0,o.2,2w.2,4.1,9.0,4.0,5.0,q.1,6.0,48.1,r.h,e.0,13.7,q.a,1b.2,1d.0,3.3,3.1,i.0,m.1,1v.5,3.1,3.1,d.0,9.0,10.0,c.0,1g.0,2.2,3.1,6.1,2.0,s.0,f.1,6.1,2.0,2t.4,a.2,3e.0,3.0,5.0,fn5.0,44.g,fy.f,4.0,d.f,z.0,3.0,4q.0,8.0,7.0,c.0,10.0,2.0,1c.0,1a.1,1w.0,m.2,ea.0,6b.0,46.4,sm.5,2.15,2.8,g7.2,2.1,6.3,15.2,5.0,4m.1,fy.3,as.1,4a.a,1e.3,3g.0,1j.e,16.0,3.1,b.2,1e.3,3.1,3.0,5.0,b.0,1f.2,11.4,2.7,1r.0,d.1,1h.8,b.3,3.0,2o.2,3.0,2.1,7.0,4h.0,4.7,m.1,1m.1,4.0,12.6,4.4,5g.7,3.2,2.0,o.0,2d.5,2.0,5.1,2.1,6n.3,7.1,2.1,s.1,2e.7,3.0,2.1,2z.0,2.0,3.5,2.0,2u.2,3.3,2.4,78.8,2.1,75.1,2.0,5.0,41.3,3.1,5.0,x.9,15.5,3.3,9.0,a.5,3.2,1b.c,2.1,bb.6,2.5,2.0,2b.l,3.6,2.1,2.1,3f.5,4.0,2.1,2.6,2.0,21.1,4.0,2.0,9o.1,470.8,at4.4,1o.6,a.3,ss.0,1s.g,1t.1,2.1,cng.3,2.6,2.1,2hr.1,2.3,3ml.19,3.m,f5.2,a.f,3.6,v.3,45.2,1j0.1i,5.1d,9.0,f.0,n.4,2.e,11t.6,2.g,3.6,2.1,2.4,7a.d,a9.0,1q.3,15t.6,32.7,240.4,gx6q.0,v.2n,3l.6n';
const UNASSIGNED = 'oo.1,7.3,8.0,2.0,l.0,b2.0,13.1,1f.1,4.0,1k.7,s.3,7.a,7j.0,1p.1,2u.d,1o.1,1e.1,g.0,t.1,2.0,c.4,w.0,3.5,6l.0,9.1,3.1,n.0,8.0,2.2,5.1,a.1,3.1,5.7,2.3,3.0,6.1,q.1,4.0,7.3,3.1,n.0,8.0,3.0,3.0,3.1,2.0,6.3,3.1,4.2,2.6,5.0,2.6,i.9,4.0,a.0,4.0,n.0,8.0,3.0,6.1,b.0,4.0,4.1,2.e,5.1,d.6,8.0,4.0,9.1,3.1,n.0,8.0,3.0,6.1,a.1,3.1,4.6,4.3,3.0,6.1,j.9,3.0,7.2,4.0,5.2,3.0,2.0,3.2,3.2,4.2,d.3,6.2,4.0,5.1,2.5,2.d,m.4,e.0,4.0,o.0,h.1,a.0,4.0,5.6,3.0,4.1,2.1,5.1,b.6,n.0,4.0,o.0,b.0,6.1,a.0,4.0,5.6,3.5,3.0,5.1,b.0,3.c,e.0,4.0,1g.0,4.0,7.3,h.1,r.0,4.0,j.2,p.0,a.0,2.1,8.2,2.3,7.0,2.0,9.5,b.1,4.b,1n.3,u.10,3.0,2.0,6.0,p.0,2.0,o.1,6.0,2.0,7.1,b.1,5.v,21.0,11.3,14.0,11.0,g.0,e.10,5j.0,2.4,2.1,ai.0,5.1,8.0,2.0,5.1,16.0,5.1,y.0,5.1,8.0,2.0,5.1,g.0,1m.0,5.1,1w.1,x.2,r.5,2f.1,7.1,im.2,2i.6,n.8,p.8,l.b,e.0,4.0,3.b,2n.1,b.5,b.5,r.5,2i.6,18.4,1z.9,w.0,d.3,d.3,2.2,17.1,6.a,19.3,r.5,c.2,1r.1,1u.0,u.1,c.5,b.5,f.1,w.1c,26.2,1c.0,39.7,1p.2,g.2,1p.6,18.1,c.7,18.4,ev.1,7.1,13.1,7.1,9.0,2.0,2.0,2.0,w.1,1i.0,g.0,f.1,7.0,k.1,4.0,a.0,2u.0,d.1,s.0,e.2,y.e,y.e,3x.3,ig.o,c.k,1ed.1,x.0,9q.4,1a.0,2.4,2.1,1l.6,3.d,p.8,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,3j.x,r.0,2i.b,5z.p,d.3,1t.0,2f.1,2w.4,18.0,2n.0,2d.b,1c.0,mlq.2,1k.8,9p.j,55.7,5o.4,3.0,2.0,6.n,1o.2,b.5,1l.7,1z.7,d.5,39.a,v.2,27.0,c.3,y.0,1k.8,f.1,b.1,2w.n,t.9,7.1,7.1,7.8,8.0,8.0,1p.3,3j.1,b.5,8md.b,o.3,1e.3,6sv.1,2z.11,8.b,6.4,r.0,6.0,2.0,3.0,3.0,3i.f,ce.1,1j.6,2.v,17.5,1g.0,k.0,5.3,6.0,3s.1,2.0,5b.2,7.1,7.1,7.1,4.2,8.0,8.9,6.1,d.0,r.0,k.0,3.0,g.1,f.x,3g.4,4.3,1a.2,2h.0,e.2,2.1a,1b.3l,u.2,1e.e,t.3,11.8,v.4,18.4,v.0,12.3,f.15,4f.1,b.5,11.3,11.3,15.7,1h.a,d.0,g.0,8.0,3.0,c.0,g.0,8.0,3.1u,8o.8,n.9,9.n,7.0,17.0,a.1w,7.1,2.0,19.0,3.2,2.1,o.0,21.7,a.1b,k.0,3.4,y.2,s.4,2.1r,1l.3,l.1,1f.0,3.4,9.0,4.0,u.1,4.3,b.6,a.6,1t.v,14.3,d.8,1j.2,u.1,s.4,r.6,5.b,8.27,22.1i,1g.c,1g.6,1b.7,b.85,w.0,17.0,4.1,3.25,15.7,17.l,r.11,t.j,o.8,27.3,11.8,1x.9,2.1,q.6,b.5,1i.0,j.7,14.8,2p.0,l.a,j.0,19.1s,8.0,2.0,5.0,g.0,c.5,1o.4,b.5,5.0,9.1,3.1,n.0,8.0,3.0,6.0,b.1,3.1,4.1,2.5,2.4,8.1,8.2,6.3u,2l.0,6.t,21.7,b.4l,1j.1,13.x,1y.a,b.5,e.i,1n.5,b.1h,s.1,g.3,o.54,1p.2r,2c.b,9.1,2.1,9.0,3.0,v.0,3.1,d.8,b.1x,9.1,1b.1,c.q,21.7,2c.c,22.7a,a.0,1a.0,f.9,u.2,x.1,n.0,f.20,8.0,3.0,19.2,2.0,3.0,a.7,b.5,7.0,3.0,12.0,3.0,7.6,b.8l,q.52,2.e,1f.c,po.2t,34.0,6.a,5h.217,2s.c,ts.0,a.346,g8.6ns,fu.6,w.0,b.3,2a.0,b.5,v.1,7.9,1z.9,b.0,8.0,m.4,k.j3,2k.2s,24.3,1m.6,i.1r,6.a,3.d,4qh.7,yf.15,a.6w6,5.0,8.0,3.0,84.18,4.g,5.7,b1.1s3,30.4,e.2,a.6,b.1,9.3mj,1b.1,o.8,39.1n,6v.9,14.1,5f.k,1z.49,l.b,2g.8,q.3q,2e.0,20.0,3.1,2.1,3.1,5.0,d.0,2.0,8.0,1u.0,5.1,9.0,8.0,t.0,5.0,6.0,2.2,8.0,9h.1,85.1,jj.e,6.0,g.un,w.68,8.0,i.1,8.0,3.0,6.5w,1a.2,f.1,b.3,3.8v,w.g,1n.4,2.yn,8.0,5.0,3.0,g.0,5i.1,h.14,25.3,b.3,3.ls,1x.23,1q.5d,5.0,s.0,3.0,2.1,2.0,b.0,5.0,2.0,2.5,2.3,2.0,2.0,2.0,4.0,3.0,2.1,2.0,2.0,2.0,2.0,2.0,3.0,2.1,5.0,8.0,5.0,5.0,2.0,b.0,i.4,4.0,6.0,i.1f,3.7h,19.3,2t.b,g.1,g.0,g.0,12.9,4v.1j,u.c,19.3,a.6,3.d,7.49,rd.4,h.2,e.2,39.b,2i.6,d.3,2.e,d.3,1l.7,b.5,15.7,v.1,3.25,9h.b,f.1,6.2,6.2,8.8,u.2,c.4,7.9,b.5,9.7,8.8,44.0,1k.10,b.sl,wyp.v,37e.6,67.1,4g3.d,5rm.2e6,f3.15t,3t8.fcfp,2.t,2p.3j,6p.1e6n,1ekf.1,1ekf.1';
const TITLE_SPECIAL = {0xdf: '\u{53}\u{73}', 0x1c4: '\u{1c5}', 0x1c5: '\u{1c5}', 0x1c6: '\u{1c5}', 0x1c7: '\u{1c8}', 0x1c8: '\u{1c8}', 0x1c9: '\u{1c8}', 0x1ca: '\u{1cb}', 0x1cb: '\u{1cb}', 0x1cc: '\u{1cb}', 0x1f1: '\u{1f2}', 0x1f2: '\u{1f2}', 0x1f3: '\u{1f2}', 0x587: '\u{535}\u{582}', 0x10d0: '\u{10d0}', 0x10d1: '\u{10d1}', 0x10d2: '\u{10d2}', 0x10d3: '\u{10d3}', 0x10d4: '\u{10d4}', 0x10d5: '\u{10d5}', 0x10d6: '\u{10d6}', 0x10d7: '\u{10d7}', 0x10d8: '\u{10d8}', 0x10d9: '\u{10d9}', 0x10da: '\u{10da}', 0x10db: '\u{10db}', 0x10dc: '\u{10dc}', 0x10dd: '\u{10dd}', 0x10de: '\u{10de}', 0x10df: '\u{10df}', 0x10e0: '\u{10e0}', 0x10e1: '\u{10e1}', 0x10e2: '\u{10e2}', 0x10e3: '\u{10e3}', 0x10e4: '\u{10e4}', 0x10e5: '\u{10e5}', 0x10e6: '\u{10e6}', 0x10e7: '\u{10e7}', 0x10e8: '\u{10e8}', 0x10e9: '\u{10e9}', 0x10ea: '\u{10ea}', 0x10eb: '\u{10eb}', 0x10ec: '\u{10ec}', 0x10ed: '\u{10ed}', 0x10ee: '\u{10ee}', 0x10ef: '\u{10ef}', 0x10f0: '\u{10f0}', 0x10f1: '\u{10f1}', 0x10f2: '\u{10f2}', 0x10f3: '\u{10f3}', 0x10f4: '\u{10f4}', 0x10f5: '\u{10f5}', 0x10f6: '\u{10f6}', 0x10f7: '\u{10f7}', 0x10f8: '\u{10f8}', 0x10f9: '\u{10f9}', 0x10fa: '\u{10fa}', 0x10fd: '\u{10fd}', 0x10fe: '\u{10fe}', 0x10ff: '\u{10ff}', 0x1f80: '\u{1f88}', 0x1f81: '\u{1f89}', 0x1f82: '\u{1f8a}', 0x1f83: '\u{1f8b}', 0x1f84: '\u{1f8c}', 0x1f85: '\u{1f8d}', 0x1f86: '\u{1f8e}', 0x1f87: '\u{1f8f}', 0x1f88: '\u{1f88}', 0x1f89: '\u{1f89}', 0x1f8a: '\u{1f8a}', 0x1f8b: '\u{1f8b}', 0x1f8c: '\u{1f8c}', 0x1f8d: '\u{1f8d}', 0x1f8e: '\u{1f8e}', 0x1f8f: '\u{1f8f}', 0x1f90: '\u{1f98}', 0x1f91: '\u{1f99}', 0x1f92: '\u{1f9a}', 0x1f93: '\u{1f9b}', 0x1f94: '\u{1f9c}', 0x1f95: '\u{1f9d}', 0x1f96: '\u{1f9e}', 0x1f97: '\u{1f9f}', 0x1f98: '\u{1f98}', 0x1f99: '\u{1f99}', 0x1f9a: '\u{1f9a}', 0x1f9b: '\u{1f9b}', 0x1f9c: '\u{1f9c}', 0x1f9d: '\u{1f9d}', 0x1f9e: '\u{1f9e}', 0x1f9f: '\u{1f9f}', 0x1fa0: '\u{1fa8}', 0x1fa1: '\u{1fa9}', 0x1fa2: '\u{1faa}', 0x1fa3: '\u{1fab}', 0x1fa4: '\u{1fac}', 0x1fa5: '\u{1fad}', 0x1fa6: '\u{1fae}', 0x1fa7: '\u{1faf}', 0x1fa8: '\u{1fa8}', 0x1fa9: '\u{1fa9}', 0x1faa: '\u{1faa}', 0x1fab: '\u{1fab}', 0x1fac: '\u{1fac}', 0x1fad: '\u{1fad}', 0x1fae: '\u{1fae}', 0x1faf: '\u{1faf}', 0x1fb2: '\u{1fba}\u{345}', 0x1fb3: '\u{1fbc}', 0x1fb4: '\u{386}\u{345}', 0x1fb7: '\u{391}\u{342}\u{345}', 0x1fbc: '\u{1fbc}', 0x1fc2: '\u{1fca}\u{345}', 0x1fc3: '\u{1fcc}', 0x1fc4: '\u{389}\u{345}', 0x1fc7: '\u{397}\u{342}\u{345}', 0x1fcc: '\u{1fcc}', 0x1ff2: '\u{1ffa}\u{345}', 0x1ff3: '\u{1ffc}', 0x1ff4: '\u{38f}\u{345}', 0x1ff7: '\u{3a9}\u{342}\u{345}', 0x1ffc: '\u{1ffc}', 0xfb00: '\u{46}\u{66}', 0xfb01: '\u{46}\u{69}', 0xfb02: '\u{46}\u{6c}', 0xfb03: '\u{46}\u{66}\u{69}', 0xfb04: '\u{46}\u{66}\u{6c}', 0xfb05: '\u{53}\u{74}', 0xfb06: '\u{53}\u{74}', 0xfb13: '\u{544}\u{576}', 0xfb14: '\u{544}\u{565}', 0xfb15: '\u{544}\u{56b}', 0xfb16: '\u{54e}\u{576}', 0xfb17: '\u{544}\u{56d}'};
const RE_IGNORECASE_EXTRA = {0x69: [0x130, 0x131], 0x6b: [0x212a], 0x73: [0x17f]};
// END unicode tables

/** The unicodedata.unidata_version the tables come from. */
const UNIDATA_VERSION = '14.0.0';

/** Decode a delta/base-36 range table into sorted [start, end] pairs (Int32Array). */
function decodeRanges(table) {
  const out = [];
  if (table) {
    let prev = 0;
    for (const part of table.split(',')) {
      const [d, len] = part.split('.').map((x) => parseInt(x, 36));
      const a = prev + d;
      out.push(a, a + len);
      prev = a + len;
    }
  }
  return Int32Array.from(out);
}

function inRanges(r, cp) {
  let lo = 0;
  let hi = r.length / 2 - 1;
  while (lo <= hi) {
    const mid = (lo + hi) >> 1;
    if (cp < r[2 * mid]) hi = mid - 1;
    else if (cp > r[2 * mid + 1]) lo = mid + 1;
    else return true;
  }
  return false;
}

/** A JS character-class body (`u` flag) for a decoded range table. */
function classBody(r) {
  const hex = (c) => `\\u{${c.toString(16)}}`;
  let s = '';
  for (let i = 0; i < r.length; i += 2) s += r[i] === r[i + 1] ? hex(r[i]) : `${hex(r[i])}-${hex(r[i + 1])}`;
  return s;
}

const NONPRINT_R = decodeRanges(NONPRINT);
const DIGIT_R = decodeRanges(DIGIT);
const ALNUM_R = decodeRanges(ALNUM);
const UPPER_R = decodeRanges(UPPER);
const LOWER_R = decodeRanges(LOWER);
const TITLE_R = decodeRanges(TITLE);
const CASE_IGNORABLE_R = decodeRanges(CASE_IGNORABLE);
const UNASSIGNED_R = decodeRanges(UNASSIGNED);

/** code point → digit value of every Nd character (re `\d`, int(), float()). */
const ND_DIGIT = new Map();
for (const z of ND_ZEROS) for (let k = 0; k < 10; k += 1) ND_DIGIT.set(z + k, k);

/** str.isspace(): the ASCII ones (\t \n \v \f \r, \x1c–\x1f, space) + PY_SPACE_HI. */
const PY_SPACE = new Set([0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x1c, 0x1d, 0x1e, 0x1f, 0x20, ...PY_SPACE_HI]);

/** str.isprintable() of one code point (U+007F DEL and the C0 controls are not printable). */
function isPrintable(cp) {
  if (cp < 0x7f) return cp >= 0x20;
  if (cp === 0x7f) return false;
  return !inRanges(NONPRINT_R, cp);
}

/** str.isspace() of one code point. */
const isSpace = (cp) => PY_SPACE.has(cp);
/** Digit value of an Nd code point (unicodedata.decimal), or -1. */
const digitValue = (cp) => (ND_DIGIT.has(cp) ? ND_DIGIT.get(cp) : -1);
/** str.isdigit() of one code point (Numeric_Type Decimal or Digit: also ² ① …). */
const isDigitChar = (cp) => inRanges(DIGIT_R, cp);
/** str.isalnum() of one code point. */
const isAlnumChar = (cp) => inRanges(ALNUM_R, cp);
/** re `\w` (str pattern): str.isalnum() or '_'. */
const isWordChar = (cp) => cp === 0x5f || inRanges(ALNUM_R, cp);
const isUpperFlag = (cp) => inRanges(UPPER_R, cp);
const isLowerFlag = (cp) => inRanges(LOWER_R, cp);
const isTitleFlag = (cp) => inRanges(TITLE_R, cp);
/** _PyUnicode_IsCased: Lowercase ∪ Uppercase ∪ Lt. */
const isCased = (cp) => isLowerFlag(cp) || isUpperFlag(cp) || isTitleFlag(cp);
const isCaseIgnorable = (cp) => inRanges(CASE_IGNORABLE_R, cp);
/** Category Cn in unicodedata 14.0.0. */
const isUnassigned = (cp) => inRanges(UNASSIGNED_R, cp);

/** Python's `\d` (any Nd digit of the bot's Unicode database) as a JS character class body (`u` flag). */
const ND_CLASS = ND_ZEROS.map((z) => `\\u{${z.toString(16)}}-\\u{${(z + 9).toString(16)}}`).join('');
/** Python's `\s` (str.isspace()) as a JS character class body (`u` flag). */
const SPACE_CLASS = classBody(Int32Array.from([...PY_SPACE].sort((a, b) => a - b).flatMap((c) => [c, c])));
/** Python's `\w` (str.isalnum() + '_') as a JS character class body (`u` flag). */
const WORD_CLASS = `_${classBody(ALNUM_R)}`;
/** Python's `\b` for a JS regex with the `u` flag (a \w / non-\w transition, string ends count as non-\w). */
const WORD_BOUNDARY = `(?:(?<=[${WORD_CLASS}])(?![${WORD_CLASS}])|(?<![${WORD_CLASS}])(?=[${WORD_CLASS}]))`;

// ── str methods ─────────────────────────────────────────────────────────────

/** The str methods take a str only (like `s.toUpperCase()` / `s.trim()`, which throw for anything else). */
function strArg(s, name) {
  if (typeof s !== 'string') throw new TypeError(`str.${name}() needs a str, got ${s === null ? 'null' : typeof s}`);
  return s;
}
const cpsOf = (s) => Array.from(s, (ch) => ch.codePointAt(0));
const ASCII_RE = /^[\x00-\x7f]*$/;   // eslint-disable-line no-control-regex

/** str.isdigit() */
function pyIsdigit(s) {
  const cps = cpsOf(strArg(s, 'isdigit'));
  return cps.length > 0 && cps.every(isDigitChar);
}

/** str.isupper(): at least one cased character and no lowercase / titlecase one. */
function pyIsupper(s) {
  let cased = false;
  for (const cp of cpsOf(strArg(s, 'isupper'))) {
    if (isLowerFlag(cp) || isTitleFlag(cp)) return false;
    if (!cased && isUpperFlag(cp)) cased = true;
  }
  return cased;
}

/**
 * The full case mapping of one character as CPython 3.11 has it: Node's mapping, unless the
 * character or a character of its mapping is unassigned in Unicode 14.0 (then there is none).
 */
function mapChar(ch, upper) {
  const m = upper ? ch.toUpperCase() : ch.toLowerCase();
  if (m === ch) return ch;
  if (isUnassigned(ch.codePointAt(0))) return ch;
  for (const c of m) if (isUnassigned(c.codePointAt(0))) return ch;
  return m;
}

/** handle_capital_sigma: Σ at index i is final when a cased char precedes it and none follows (case-ignorables skipped). */
function finalSigma(cps, i) {
  let j = i - 1;
  while (j >= 0 && isCaseIgnorable(cps[j])) j -= 1;
  let fin = j >= 0 && isCased(cps[j]);
  if (fin && i + 1 < cps.length) {
    j = i + 1;
    while (j < cps.length && isCaseIgnorable(cps[j])) j += 1;
    fin = j === cps.length || !isCased(cps[j]);
  }
  return fin;
}

/** lower_ucs4 at index i. */
function lowerAt(cps, i) {
  if (cps[i] === 0x3a3) return finalSigma(cps, i) ? 'ς' : 'σ';
  return mapChar(String.fromCodePoint(cps[i]), false);
}

/** str.lower() */
function pyLower(s) {
  strArg(s, 'lower');
  if (ASCII_RE.test(s)) return s.toLowerCase();
  const cps = cpsOf(s);
  let out = '';
  for (let i = 0; i < cps.length; i += 1) out += lowerAt(cps, i);
  return out;
}

/** str.upper() */
function pyUpper(s) {
  strArg(s, 'upper');
  if (ASCII_RE.test(s)) return s.toUpperCase();
  let out = '';
  for (const ch of s) out += mapChar(ch, true);
  return out;
}

/** str.capitalize() (3.8+): title case of the first character, lower() of the rest (Final_Sigma in context). */
function pyCapitalize(s) {
  const cps = cpsOf(strArg(s, 'capitalize'));
  if (!cps.length) return '';
  const first = String.fromCodePoint(cps[0]);
  let out = Object.prototype.hasOwnProperty.call(TITLE_SPECIAL, cps[0]) ? TITLE_SPECIAL[cps[0]] : mapChar(first, true);
  for (let i = 1; i < cps.length; i += 1) out += lowerAt(cps, i);
  return out;
}

/** str.strip() / lstrip() / rstrip() with no argument (str.isspace() characters). */
function pyStrip(s) {
  const cps = Array.from(strArg(s, 'strip'));
  let a = 0;
  let b = cps.length;
  while (a < b && PY_SPACE.has(cps[a].codePointAt(0))) a += 1;
  while (b > a && PY_SPACE.has(cps[b - 1].codePointAt(0))) b -= 1;
  return cps.slice(a, b).join('');
}
function pyRstrip(s) {
  const cps = Array.from(strArg(s, 'rstrip'));
  let b = cps.length;
  while (b > 0 && PY_SPACE.has(cps[b - 1].codePointAt(0))) b -= 1;
  return cps.slice(0, b).join('');
}
function pyLstrip(s) {
  const cps = Array.from(strArg(s, 'lstrip'));
  let a = 0;
  while (a < cps.length && PY_SPACE.has(cps[a].codePointAt(0))) a += 1;
  return cps.slice(a).join('');
}

const hex = (c, n) => c.toString(16).padStart(n, '0');

/** repr(str) — CPython's unicode_repr: quote choice, \\ \t \n \r, \xhh / \uhhhh / \Uhhhhhhhh for non-printables. */
function pyStrRepr(s) {
  s = String(s);
  const q = s.includes("'") && !s.includes('"') ? '"' : "'";
  let out = q;
  for (const ch of s) {
    const c = ch.codePointAt(0);
    if (ch === q || ch === '\\') out += `\\${ch}`;
    else if (ch === '\t') out += '\\t';
    else if (ch === '\n') out += '\\n';
    else if (ch === '\r') out += '\\r';
    else if (isPrintable(c)) out += ch;
    else if (c <= 0xff) out += `\\x${hex(c, 2)}`;
    else if (c <= 0xffff) out += `\\u${hex(c, 4)}`;
    else out += `\\U${hex(c, 8)}`;
  }
  return out + q;
}

module.exports = {
  UNIDATA_VERSION, ND_ZEROS, ND_DIGIT, PY_SPACE, ND_CLASS, SPACE_CLASS, WORD_CLASS, WORD_BOUNDARY, TITLE_SPECIAL, RE_IGNORECASE_EXTRA,
  isPrintable, isSpace, digitValue, isDigitChar, isAlnumChar, isWordChar, isUpperFlag, isLowerFlag, isTitleFlag,
  isCased, isCaseIgnorable, isUnassigned,
  pyIsdigit, pyIsupper, pyLower, pyUpper, pyCapitalize, pyStrip, pyLstrip, pyRstrip, pyStrRepr,
};
