/**
 * binanceTrader.js vs binance_trader.py — request-for-request replay (fixtures/scenarios_binance.json,
 * generated by py/gen_trader_scenarios.py binance): urlencoded + HMAC-signed query strings
 * (then requoted by yarl exactly like aiohttp does with a str URL), batchOrders with the
 * legacy fallback, dual-side / one-way detection, leverage halving, SL-by-orderId with the
 * safety close, -2021 adaptive TP re-pricing, all-TP-success rule, reads, closes, cancels,
 * time sync and the fapi1..4 endpoint probe — results, sleeps and log markers equal.
 */
import { describe, it, expect } from 'vitest';
import { createRequire } from 'module';
const req = createRequire(import.meta.url);
const BN = req('../../services/exchanges/binanceTrader.js');
const { runScenario } = req('./replay.js');
const { loadFixture, makeClock } = req('./helpers.js');

const ROWS = loadFixture('scenarios_binance.json');
const OPT = { tp2: 'tp2', tp3: 'tp3', risk_mode: 'riskMode', order_type: 'orderType', trade_id: 'tradeId', user_id: 'userId', allow_low_notional_boost: 'allowLowNotionalBoost' };
const camel = (kw) => Object.fromEntries(Object.entries(kw || {}).map(([k, v]) => [OPT[k] || k, v]));

const CALLS = {
  place_trade: (t, a, kw) => t.placeTrade(...a.slice(0, 9), camel(kw)),
  set_trailing_sl: (t, a) => t.setTrailingSl(...a),
  set_breakeven: (t, a) => t.setBreakeven(...a),
  place_sl_tp_for_position: (t, a) => t.placeSlTpForPosition(...a),
  close_position: (t, a) => t.closePosition(...a),
  cancel_all_orders: (t, a) => t.cancelAllOrders(...a),
  cancel_tp_orders_only: (t, a) => t.cancelTpOrdersOnly(...a),
  cancel_order: (t, a) => t.cancelOrder(...a),
  get_positions: (t, a) => t.getPositions(...a),
  get_balance: (t, a) => t.getBalance(...a),
  get_last_price: (t, a) => t.getLastPrice(...a),
  get_closed_pnl: (t, a) => t.getClosedPnl(...a),
  get_open_orders: (t, a) => t.getOpenOrders(...a),
  get_dashboard: (t, a) => t.getDashboard(...a),
  test_connection: (t, a) => t.testConnection(...a),
  sync_time: (t) => t.syncTime(),
  _find_working_binance_url: (t) => t.findWorkingBinanceUrl(),
};

describe('binance_trader replay parity', () => {
  for (const { scenario: sc, expected: exp } of ROWS) {
    it(sc.name, async () => {
      const { out, trader } = await runScenario(sc, (o) => BN.createBinanceTrader(o), (t, s) => {
        const fn = CALLS[s.call];
        if (!fn) throw new Error(`no JS mapping for ${s.call}`);
        return fn(t, s.args, s.kwargs);
      }, (t, s) => { if (s.state && s.state.binance_offset_ms !== undefined) t._state.timeOffsetMs = s.state.binance_offset_ms; });
      expect(out.requests, 'requests').toEqual(exp.requests);
      if (exp.raised) expect(out.raised, 'raised').toEqual(exp.raised);
      else expect(out.result, 'result').toEqual(exp.result);
      expect(out.sleeps, 'sleeps').toEqual(exp.sleeps);
      expect(out.markers, 'log markers').toEqual(exp.markers);
      expect(out.saved.metrics, 'metrics').toEqual(exp.saved.metrics);
      expect(trader._state.baseUrl, 'BASE_URL').toBe(exp.final.binance_base);
      expect(trader._state.timeOffsetMs, 'time offset').toBe(exp.final.binance_offset);
    });
  }
});

describe('binance signature vectors (bot _sign / _build_query)', () => {
  const V = loadFixture('pure_vectors.json');
  // python: bn._binance_time_offset_ms = -120; time.time = lambda: 1767225600.123; bn._build_query(KEY, SECRET, params)
  const PARAMS = [
    { symbol: 'BTCUSDT', side: 'BUY', type: 'LIMIT', quantity: '0.002', price: '87490.5', timeInForce: 'GTC' },
    // json.dumps([{"symbol": "BTCUSDT", "side": "BUY", "type": "MARKET", "quantity": "0.002"}])
    { batchOrders: '[{"symbol": "BTCUSDT", "side": "BUY", "type": "MARKET", "quantity": "0.002"}]' },
  ];
  it('_build_query: urlencode + HMAC-SHA256 hex signature, server offset applied', () => {
    const clock = makeClock(1767225600.123);
    const t = BN.createBinanceTrader({ now: clock.now, transport: async () => { throw new Error('no network'); } });
    t._state.timeOffsetMs = -120;
    PARAMS.forEach((p, i) => {
      const [qs, headers] = t._buildQuery(V.keys.key, V.keys.secret, p);
      expect(qs).toBe(V.binance_build_query[i].qs);
      expect(headers).toEqual(V.binance_build_query[i].headers);
      const [body, sig] = qs.split('&signature=');
      expect(BN.binanceSign(body, V.keys.secret)).toBe(sig);
    });
  });
  it('humanizer on str(dict) and JSON inputs', () => {
    for (const [s, exp] of V.humanize_binance) expect(BN.humanizeBinanceError(s), s).toBe(exp);
  });
  it('symbol mapping and price multiplier (to_binance_symbol / binance_price_multiplier)', () => {
    for (const row of V.symbols) {
      expect(BN.toBinanceSymbol(row[0]), row[0]).toBe(row[5]);
      expect(BN.binancePriceMultiplier(row[0]), row[0]).toBe(row[6]);
    }
  });
});
