/**
 * bingxTrader.js vs bingx_trader.py — request-for-request replay (fixtures/scenarios_bingx.json,
 * generated by py/gen_trader_scenarios.py bingx): signed query strings (sorted, quote(safe='')
 * + HMAC), batchOrders JSON, legacy flow with 0.2 s fill polling, SL/TP retries, safety close,
 * trailing SL, closes, cancels and the read endpoints — results, sleeps and log markers equal.
 */
import { describe, it, expect, afterEach } from 'vitest';
import { createRequire } from 'module';
const req = createRequire(import.meta.url);
const BX = req('../../services/exchanges/bingxTrader.js');
const SYM = req('../../services/marketData/symbolMap.js');
const { runScenario } = req('./replay.js');
const { loadFixture } = req('./helpers.js');

const ROWS = loadFixture('scenarios_bingx.json');
const OPT = { tp2: 'tp2', tp3: 'tp3', risk_mode: 'riskMode', order_type: 'orderType', trade_id: 'tradeId', user_id: 'userId', allow_low_notional_boost: 'allowLowNotionalBoost' };
const camel = (kw) => Object.fromEntries(Object.entries(kw || {}).map(([k, v]) => [OPT[k] || k, v]));

const CALLS = {
  place_trade: (t, a, kw) => t.placeTrade(...a.slice(0, 9), camel(kw)),
  set_trailing_sl: (t, a) => t.setTrailingSl(...a),
  set_breakeven: (t, a) => t.setBreakeven(...a),
  place_sl_tp_for_position: (t, a) => t.placeSlTpForPosition(...a),
  close_position: (t, a) => t.closePosition(...a),
  cancel_all_orders: (t, a) => t.cancelAllOrders(...a),
  cancel_tp_orders_only: (t, a) => t.cancelTpOrdersOnly(...a),
  cancel_order: (t, a) => t.cancelOrder(...a),
  get_positions: (t, a) => t.getPositions(...a),
  get_balance: (t, a) => t.getBalance(...a),
  get_last_price: (t, a) => t.getLastPrice(...a),
  get_closed_pnl: (t, a) => t.getClosedPnl(...a),
  get_open_orders: (t, a) => t.getOpenOrders(...a),
  get_dashboard: (t, a) => t.getDashboard(...a),
  test_connection: (t, a) => t.testConnection(...a),
  sync_time: (t) => t.syncTime(),
};

afterEach(() => SYM._setLive([]));

describe('bingx_trader replay parity', () => {
  for (const { scenario: sc, expected: exp } of ROWS) {
    it(sc.name, async () => {
      SYM._setLive((sc.state && sc.state.live_bingx) || []);
      const { out } = await runScenario(sc, (o) => BX.createBingxTrader(o), (t, s) => {
        const fn = CALLS[s.call];
        if (!fn) throw new Error(`no JS mapping for ${s.call}`);
        return fn(t, s.args, s.kwargs);
      }, (t, s) => { if (s.state && s.state.bingx_offset_ms !== undefined) t._state.timeOffsetMs = s.state.bingx_offset_ms; });
      expect(out.requests, 'requests').toEqual(exp.requests);
      if (exp.raised) expect(out.raised, 'raised').toEqual(exp.raised);
      else expect(out.result, 'result').toEqual(exp.result);
      expect(out.sleeps, 'sleeps').toEqual(exp.sleeps);
      expect(out.markers, 'log markers').toEqual(exp.markers);
      expect(out.saved.metrics, 'metrics').toEqual(exp.saved.metrics);
    });
  }
});

describe('bingx signature vectors (bot _sign / _build_query)', () => {
  const V = loadFixture('pure_vectors.json');
  it('_sign over sorted, url-encoded params', () => {
    // python -c "import bingx_trader as b; print(b._sign({'symbol':'BTC-USDT','timestamp':'1'}, 's'))"
    for (const { params, sign } of V.bingx_sign) expect(BX.bingxSign(params, V.keys.secret)).toBe(sign);
  });
  it('_build_query with the server offset', () => {
    const { makeClock } = req('./helpers.js');
    const clock = makeClock(1767225600.123);
    const t = BX.createBingxTrader({ now: clock.now, transport: async () => { throw new Error('no network'); } });
    t._state.timeOffsetMs = 250;
    const [qs, headers] = t._buildQuery(V.keys.key, V.keys.secret, { symbol: 'BTC-USDT', side: 'BUY', positionSide: 'LONG', type: 'MARKET', quantity: '0.5' });
    expect(qs).toBe(V.bingx_build_query.qs);
    expect(headers).toEqual(V.bingx_build_query.headers);
  });
  it('humanizer on str(dict) inputs', () => {
    for (const [s, exp] of V.humanize_bingx) expect(BX.humanizeBingxError(s), s).toBe(exp);
  });
});
