/**
 * okxTrader.js vs okx_trader.py — request-for-request replay (fixtures/scenarios_okx.json,
 * generated by py/gen_trader_scenarios.py okx): OK-ACCESS-* headers (base64 HMAC over the ISO
 * timestamp computed once per request + METHOD + path?query + json body, server offset
 * applied), attachAlgoOrds SL + TP1 with the 51000/51001/"attachalgo" legacy fallback, SL
 * algo ×3 and the safety close, TP2/TP3 algos ×3, ctVal contracts, cancel-all with the algo
 * endpoints, close + algo cleanup, readers and their uncaught-exception quirks.
 */
import { describe, it, expect } from 'vitest';
import { createRequire } from 'module';
const req = createRequire(import.meta.url);
const OK = req('../../services/exchanges/okxTrader.js');
const { runScenario } = req('./replay.js');
const { loadFixture, makeClock } = req('./helpers.js');

const ROWS = loadFixture('scenarios_okx.json');
const OPT = {
  tp2: 'tp2', tp3: 'tp3', risk_mode: 'riskMode', order_type: 'orderType', trade_id: 'tradeId', user_id: 'userId',
  allow_low_notional_boost: 'allowLowNotionalBoost', passphrase: 'passphrase',
};
const camel = (kw) => Object.fromEntries(Object.entries(kw || {}).map(([k, v]) => [OPT[k] || k, v]));

const CALLS = {
  place_trade: (t, a, kw) => t.placeTrade(...a.slice(0, 9), camel(kw)),
  set_trailing_sl: (t, a) => t.setTrailingSl(...a),
  set_breakeven: (t, a) => t.setBreakeven(...a),
  place_sl_tp_for_position: (t, a) => t.placeSlTpForPosition(...a),
  close_position: (t, a) => t.closePosition(...a),
  cancel_all_orders: (t, a) => t.cancelAllOrders(...a),
  cancel_order: (t, a) => t.cancelOrder(...a),
  get_positions: (t, a) => t.getPositions(...a),
  get_balance: (t, a) => t.getBalance(...a),
  get_last_price: (t, a) => t.getLastPrice(...a),
  get_closed_pnl: (t, a) => t.getClosedPnl(...a),
  get_open_orders: (t, a) => t.getOpenOrders(...a),
  get_account_summary: (t, a) => t.getAccountSummary(...a),
  get_dashboard: (t, a) => t.getDashboard(...a),
  test_connection: (t, a) => t.testConnection(...a),
  sync_time: (t) => t.syncTime(),
  okx_sz: (t, a) => t.okxSz(...a),
};

describe('okx_trader replay parity', () => {
  for (const { scenario: sc, expected: exp } of ROWS) {
    it(sc.name, async () => {
      const { out, trader } = await runScenario(sc, (o) => OK.createOkxTrader(o), (t, s) => {
        const fn = CALLS[s.call];
        if (!fn) throw new Error(`no JS mapping for ${s.call}`);
        return fn(t, s.args, s.kwargs);
      }, (t, s) => { if (s.state && s.state.okx_offset_ms !== undefined) t._state.timeOffsetMs = s.state.okx_offset_ms; });
      expect(out.requests, 'requests').toEqual(exp.requests);
      if (exp.raised) expect(out.raised, 'raised').toEqual(exp.raised);
      else expect(out.result, 'result').toEqual(exp.result);
      expect(out.sleeps, 'sleeps').toEqual(exp.sleeps);
      expect(out.markers, 'log markers').toEqual(exp.markers);
      expect(out.saved.metrics, 'metrics').toEqual(exp.saved.metrics);
      expect(trader._state.timeOffsetMs, 'time offset').toBe(exp.final.okx_offset);
    });
  }
});

describe('okx signature vectors (bot _sign / _iso_timestamp)', () => {
  const V = loadFixture('pure_vectors.json');
  it('_iso_timestamp: datetime 2026-01-01T00:00:00.987654Z, offsets 0 and 1500 ms', () => {
    // python: ok.datetime = <fixed 2026-01-01 00:00:00.987654 UTC>; ok._iso_timestamp(); ok._okx_time_offset_ms = 1500
    const t = Date.UTC(2026, 0, 1) / 1000 + 0.987654;
    expect(OK.isoTimestamp(t, 0)).toBe(V.okx_iso_ts[0]);
    expect(OK.isoTimestamp(t, 1500)).toBe(V.okx_iso_ts[1]);
  });
  it('_sign: base64 HMAC-SHA256 over ts + METHOD + path + body', () => {
    for (const { ts, method, path, body, sign } of V.okx_sign) expect(OK.okxSign(ts, method, path, body, V.keys.secret)).toBe(sign);
  });
  it('humanizer and symbol mapping', () => {
    for (const [s, exp] of V.humanize_okx) expect(OK.humanizeOkxError(s), s).toBe(exp);
    for (const row of V.symbols) expect(OK.toOkxSymbol(row[0]), row[0]).toBe(row[7]);
  });
  it('isoTimestamp rounds the microsecond fraction half-even like datetime.fromtimestamp', () => {
    // python -c "from datetime import datetime,timezone; print(datetime.fromtimestamp(1767225600.0005, timezone.utc))"
    expect(OK.isoTimestamp(1767225600.0005, 0)).toBe('2026-01-01T00:00:00.000Z');
    expect(OK.isoTimestamp(Number('1767225600.9999996'), 0)).toBe('2026-01-01T00:00:01.000Z');
    expect(OK.isoTimestamp(1767225600.25, -300)).toBe('2025-12-31T23:59:59.950Z');
  });
});

describe('okx demo flag (addition, default off)', () => {
  it('sends x-simulated-trading only when demo is set', async () => {
    const seen = [];
    const transport = async (r) => { seen.push(r.headers); return { status: 200, headers: { 'content-type': 'application/json' }, text: '{"code":"0","data":[]}' }; };
    const clock = makeClock();
    await OK.createOkxTrader({ transport, now: clock.now }).getOpenOrders('k', 's', 'p');
    await OK.createOkxTrader({ transport, now: clock.now, demo: true }).getOpenOrders('k', 's', 'p');
    expect(seen[0]['x-simulated-trading']).toBeUndefined();
    expect(seen[1]['x-simulated-trading']).toBe('1');
  });
});
