/**
 * Pure exchange helpers vs the bot's Python (fixtures/pure_vectors.json, generated by
 * py/gen_pure_vectors.py with the bot venv):
 *   price_precision (step/qty/price/SL/TP rounding, display), order_id_utils,
 *   tp_ladder_fit (all 4 tries), api_retry classifiers, exchange_breaker.is_transient_error,
 *   auto_trade._is_user_facing_error / _is_auth_failure, CPython repr / quote / urlencode /
 *   float() emulation.
 */
import { describe, it, expect } from 'vitest';
import { createRequire } from 'module';
const req = createRequire(import.meta.url);
const PP = req('../../services/exchanges/pricePrecision.js');
const OID = req('../../services/exchanges/orderIdUtils.js');
const TLF = req('../../services/exchanges/tpLadderFit.js');
const AR = req('../../services/exchanges/apiRetry.js');
const EB = req('../../services/exchanges/exchangeBreaker.js');
const EC = req('../../services/exchanges/errorClassify.js');
const PY = req('../../services/exchanges/pyCompat.js');
const { loadFixture } = req('./helpers.js');

const V = loadFixture('pure_vectors.json');

function run(fn) {
  try { return { ok: fn() }; } catch (e) { return { exc: e.pyType || e.name, msg: e.message }; }
}

describe('price_precision', () => {
  it('step_decimals', () => {
    // python -c "import price_precision as p; print(p.step_decimals(1e-11), p.step_decimals(2.64))"  → 0 2
    for (const [s, exp] of V.step_decimals) expect(PP.stepDecimals(s), `step=${s}`).toBe(exp);
  });

  it('round_qty (floor to step, step decimals)', () => {
    // python -c "import price_precision as p; print(p.round_qty(0.0046,0.001), p.round_qty(21.6,1.0))"  → 0.004 21
    for (const [q, s, exp] of V.round_qty) expect(run(() => PP.roundQty(q, s)), `qty=${q} step=${s}`).toEqual(exp);
  });

  it('round_price / round_price_sl / round_price_tp (Decimal half-up / floor / ceil)', () => {
    // python -c "import price_precision as p; print(p.round_price(87490.5,1), p.round_price_sl(87490.3,1,'SHORT'))" → 87491 87491
    let n = 0;
    for (const [p, t, rp, slL, slS, tpL, tpS] of V.round_price) {
      const tag = `price=${p} tick=${t}`;
      expect(run(() => PP.roundPrice(p, t)), tag).toEqual(rp);
      expect(run(() => PP.roundPriceSl(p, t, 'LONG')), `${tag} sl LONG`).toEqual(slL);
      expect(run(() => PP.roundPriceSl(p, t, 'SHORT')), `${tag} sl SHORT`).toEqual(slS);
      expect(run(() => PP.roundPriceTp(p, t, 'LONG')), `${tag} tp LONG`).toEqual(tpL);
      expect(run(() => PP.roundPriceTp(p, t, 'short')), `${tag} tp short`).toEqual(tpS);
      n++;
    }
    expect(n).toBeGreaterThan(700);
  });

  it('1000x coins: PEPE at Bybit/BingX scale and OKX scale', () => {
    // python -c "import price_precision as p; print(p.round_price(0.00000391*1000, 0.000001), p.round_price_sl(0.003905, 0.000001, 'LONG'))" → 0.003910 0.003905
    expect(PP.roundPrice(0.00000391 * 1000, 0.000001)).toBe('0.003910');
    expect(PP.roundPriceSl(0.003905, 0.000001, 'LONG')).toBe('0.003905');
    expect(PP.roundQty(2564102.56, 100)).toBe('2564100');
  });

  it('fmt_price_display', () => {
    for (const [v, exp] of V.fmt_price_display) expect(PP.fmtPriceDisplay(v), `v=${v}`).toBe(exp);
  });
});

describe('order_id_utils.compute_client_order_id', () => {
  it('deterministic ids for every (trade, user, exchange, type, attempt)', () => {
    // python -c "import order_id_utils as o; print(o.compute_client_order_id('abc', 1, 'bybit', 'entry'))"
    for (const [tid, uid, ex, ot, att, exp] of V.client_order_ids) {
      expect(OID.computeClientOrderId(tid, uid, ex, ot, att)).toBe(exp);
    }
    expect(OID.computeClientOrderId('abc', 1, 'bybit', 'entry')).toHaveLength(16);
    expect(OID.computeClientOrderId('abc', 1, 'bybit', 'entry')).toBe(OID.computeClientOrderId('abc', 1, 'bybit', 'entry', 1));
  });
});

describe('tp_ladder_fit.fit_partial_split', () => {
  it('matches Python on fixed + random cases (tries 1–4)', () => {
    const reasons = new Set();
    for (const [args, exp] of V.fit_partial_split) {
      const got = TLF.fitPartialSplit(args);
      expect(got, JSON.stringify(args)).toEqual(exp);
      reasons.add(exp.downgrade_reason);
    }
    // every branch of the fallback chain is exercised
    for (const r of ['', 'tp3_too_small_redistributed_60_40', 'tp2_tp3_too_small_single_tp', 'position_below_min_notional', 'invalid_input']) {
      expect(reasons.has(r), r).toBe(true);
    }
  });

  it('the 4 tries on one position (python one-liners)', () => {
    // python -c "import tp_ladder_fit as t; print(t.fit_partial_split(total_qty=10, price=2.0, qty_step=0.1)['n_levels_fit'])" → 3
    expect(TLF.fitPartialSplit({ total_qty: 10, price: 2.0, qty_step: 0.1 }).n_levels_fit).toBe(3);
    // price=1.5 → 30%·10·1.5=4.5 < 5 → 60/40 (9 and 6 pass)
    expect(TLF.fitPartialSplit({ total_qty: 10, price: 1.5, qty_step: 0.1 }).downgrade_reason).toBe('tp3_too_small_redistributed_60_40');
    // price=1.2 → 40%·10·1.2=4.8 < 5 → single TP
    expect(TLF.fitPartialSplit({ total_qty: 10, price: 1.2, qty_step: 0.1 }).downgrade_reason).toBe('tp2_tp3_too_small_single_tp');
    expect(TLF.fitPartialSplit({ total_qty: 10, price: 0.8, qty_step: 0.1 }).downgrade_reason).toBe('tp2_tp3_too_small_single_tp');
    expect(TLF.fitPartialSplit({ total_qty: 10, price: 0.4, qty_step: 0.1 }).downgrade_reason).toBe('position_below_min_notional');
  });

  it('get_min_notional', () => {
    for (const [e, exp] of V.min_notional) expect(TLF.getMinNotional(e)).toBe(exp);
  });
});

describe('api_retry / exchange_breaker / auto_trade classifiers', () => {
  it('is_retryable_error', () => {
    for (const [e, exp] of V.is_retryable_error) expect(AR.isRetryableError(e), String(e)).toBe(exp);
  });
  it('_result_is_retryable', () => {
    for (const [r, exp] of V.result_is_retryable) expect(AR.resultIsRetryable(r), JSON.stringify(r)).toEqual(exp);
  });
  it('is_transient_error', () => {
    for (const [e, exp] of V.is_transient_error) expect(EB.isTransientError(e === null ? 'None' : e), String(e)).toBe(exp);
  });
  it('_is_user_facing_error / _is_auth_failure', () => {
    for (const [e, exp] of V.is_user_facing_error) expect(EC.isUserFacingError(new Error(e === null ? 'None' : e)), String(e)).toBe(exp);
    for (const [e, exp] of V.is_auth_failure) expect(EC.isAuthFailure(new Error(e === null ? 'None' : e)), String(e)).toBe(exp);
  });
});

describe('CPython emulation', () => {
  it('repr(json.loads(text)) from the raw text', () => {
    for (const [t, exp] of V.json_repr) expect(PY.reprFromJsonText(t), t).toBe(exp);
  });
  it('repr(str)', () => {
    for (const [s, exp] of V.str_repr) expect(PY.pyStrRepr(s), JSON.stringify(s)).toBe(exp);
  });
  it('quote / quote_plus (safe="")', () => {
    for (const [s, q, qp] of V.quote) {
      expect(PY.pyQuote(s), s).toBe(q);
      expect(PY.pyQuotePlus(s), s).toBe(qp);
    }
  });
  it('urlencode', () => {
    // values: str(v) — True → 'True', None → 'None', 1.5 → '1.5'
    const [a, b, c] = V.urlencode;
    expect(PY.pyUrlencode(a[0])).toBe(a[1]);
    expect(PY.pyUrlencode(b[0])).toBe(b[1]);
    expect(PY.pyUrlencode(c[0])).toBe(c[1]);
  });
  it('float()', () => {
    for (const [s, exp] of V.float_parse) {
      const got = run(() => PY.pyFloat(s));
      if (exp.ok !== undefined) expect(PY.pyRepr(got.ok) === exp.ok || (exp.ok.endsWith('.0') && String(got.ok) === exp.ok.slice(0, -2)), s).toBe(true);
      else expect(got, s).toEqual({ exc: exp.exc, msg: exp.msg });
    }
  });
  it('BingX tick 10 ** (-pricePrecision)', () => {
    // python -c "print(repr(10 ** (-int(float(7)))))" → 1e-07
    // (p = 0 → int 1 in Python; numerically identical)
    for (const [p, exp] of V.pow_ticks) expect(1 / 10 ** p, `p=${p}`).toBe(Number(exp));
  });
  it('pyGet / pyIndex raise like CPython', () => {
    expect(() => PY.pyGet(null, 'x')).toThrow("'NoneType' object has no attribute 'get'");
    expect(() => PY.pyGet([], 'x')).toThrow("'list' object has no attribute 'get'");
    expect(PY.pyGet({ a: null }, 'a', 5)).toBe(null);
    expect(PY.pyGet({}, 'a', 5)).toBe(5);
    expect(() => PY.pyIndex({}, 'retMsg')).toThrow("'retMsg'");
    expect(() => PY.pyIndex([], 0)).toThrow('list index out of range');
  });
});
