/**
 * Vectors generated by the bot's own Python (gen/gen_bot_vectors.py, CPython 3.11 like
 * production; fixture bot_vectors.json):
 *   • miniapp_api._apply_multi — 840 primary × extras × direction-flag × on/off combos
 *   • miniapp_api.h_strategy flow (lock / free mutex / flags / _strategies / enabled_strategies)
 *   • user_manager._sparse_merge on 46 random override dicts (legacy & sparse & broken JSON)
 *   • handlers._common._load_sparse / _save_sparse / _update_long_field round-trips
 *   • UserSettings.grant_access (480) / check_access + _is_pro (480) / normalize_plan / parse_strategies
 */
import { describe, it, expect } from 'vitest';
import fs from 'fs';
import path from 'path';
import { createRequire } from 'module';

const nodeRequire = createRequire(import.meta.url);
const tradeCfg = nodeRequire('../../services/engine/tradeCfg.js');
const strategySet = nodeRequire('../../services/engine/strategySet.js');
const access = nodeRequire('../../services/engine/userAccess.js');
const pf = nodeRequire('../../config/planFeatures.js');

const V = JSON.parse(fs.readFileSync(path.join(process.cwd(), 'tests', 'engine', 'fixtures', 'bot_vectors.json'), 'utf8'));
const norm = (x) => JSON.parse(JSON.stringify(x));
const NOW = 1_800_000_000;

describe('_apply_multi truth table (bot vectors)', () => {
  it(`reproduces ${V.apply_multi.length} combos`, () => {
    const bad = [];
    for (const c of V.apply_multi) {
      const user = { strategy: c.primary, extra_strategies: c.extras };
      const flags = strategySet.FLAGS[c.primary];
      if (flags) { user[flags[0]] = c.pflags[0]; user[flags[1]] = c.pflags[1]; }
      strategySet.applyMulti(user, c.s, c.on);
      if (user.strategy !== c.strategy || user.extra_strategies !== c.extra_strategies) bad.push({ ...c, js: [user.strategy, user.extra_strategies] });
    }
    expect(bad).toEqual([]);
  });
});

describe('h_strategy flow (bot vectors)', () => {
  it(`reproduces ${V.strategy_flow.length} cases`, () => {
    const bad = [];
    for (const c of V.strategy_flow) {
      const user = {
        sub_plan: c.plan, sub_status: 'active', sub_expires: NOW + 86400 * 30, strategy: c.primary, extra_strategies: '',
        long_active: false, short_active: false, smc_long_active: false, smc_short_active: false,
        vol_long_active: false, vol_short_active: false, active: false,
      };
      user[strategySet.FLAGS[c.primary][0]] = true;
      const opts = { admin: false, now: NOW };
      const [wantLong, wantShort] = c.want;
      let result;
      if ((wantLong || wantShort) && strategySet.strategyLocked(user, c.s, opts)) result = 'pro_required_locked';
      else if (wantLong && wantShort && access.isMutualExclusionRequired(user, opts)) result = 'pro_required_mutex';
      else {
        const [lf, sf] = strategySet.FLAGS[c.s];
        user[lf] = wantLong; user[sf] = wantShort;
        strategySet.applyMulti(user, c.s, wantLong || wantShort);
        if (wantLong || wantShort) user.active = true;
        result = 'ok';
      }
      const flags = {};
      for (const k of Object.keys(c.flags)) flags[k] = user[k];
      const got = {
        result, strategy: user.strategy, extra_strategies: user.extra_strategies, flags,
        strategies: strategySet.strategiesState(user, opts), enabled: strategySet.enabledStrategies(user, opts).slice().sort(),
      };
      const exp = { result: c.result, strategy: c.strategy, extra_strategies: c.extra_strategies, flags: c.flags, strategies: c.strategies, enabled: c.enabled };
      if (JSON.stringify(norm(got)) !== JSON.stringify(norm(exp))) bad.push({ case: c, got });
    }
    expect(bad).toEqual([]);
  });
});

describe('_sparse_merge (bot vectors)', () => {
  it(`reproduces ${V.sparse_merge.length} random overrides`, () => {
    const bad = [];
    for (const c of V.sparse_merge) {
      const base = tradeCfg.tradeCfg(c.base);
      const merged = tradeCfg.sparseMerge(base, c.override_json);
      if (JSON.stringify(norm(merged)) !== JSON.stringify(norm(c.merged))) bad.push({ override: c.override_json, js: merged, bot: c.merged });
      if (JSON.stringify(norm(JSON.parse(tradeCfg.toJson(merged)))) !== JSON.stringify(norm(JSON.parse(c.merged_json)))) bad.push({ override: c.override_json, toJson: tradeCfg.toJson(merged), bot: c.merged_json });
    }
    expect(bad).toEqual([]);
  });

  it('_load_sparse / _save_sparse round-trips', () => {
    const bad = [];
    for (const c of V.load_sparse) {
      const loaded = tradeCfg.loadSparse(c.raw);
      if (JSON.stringify(norm(loaded)) !== JSON.stringify(norm(c.loaded))) bad.push({ raw: c.raw, js: loaded, bot: c.loaded });
      const saved = JSON.parse(tradeCfg.saveSparse(loaded));
      if (JSON.stringify(norm(saved)) !== JSON.stringify(norm(JSON.parse(c.saved)))) bad.push({ raw: c.raw, saved: tradeCfg.saveSparse(loaded), bot: c.saved });
    }
    expect(bad).toEqual([]);
  });

  it('_update_long_field + get_long_cfg', () => {
    const bad = [];
    for (const c of V.update_long) {
      const user = { ...tradeCfg.DEFAULTS, long_tf: '1h', long_interval: 3600, short_tf: '1h', short_interval: 3600, long_cfg: c.raw, short_cfg: '{}' };
      tradeCfg.updateLongField(user, 'min_rr', 2.5);
      tradeCfg.updateLongField(user, 'use_rsi', false);
      tradeCfg.updateLongField(user, 'min_volume_usdt', 1000000.0);
      if (JSON.stringify(norm(JSON.parse(user.long_cfg))) !== JSON.stringify(norm(JSON.parse(c.long_cfg)))) bad.push({ raw: c.raw, js: user.long_cfg, bot: c.long_cfg });
      const eff = tradeCfg.getLongCfg(user);
      if (JSON.stringify(norm(eff)) !== JSON.stringify(norm(c.long_cfg_eff))) bad.push({ raw: c.raw, eff, bot: c.long_cfg_eff });
    }
    expect(bad).toEqual([]);
  });
});

describe('grant_access / check_access / normalize_plan (bot vectors)', () => {
  it(`grant_access base rule — ${V.grant_access.length} cases`, () => {
    const bad = [];
    for (const c of V.grant_access) {
      const user = { sub_status: c.status, sub_plan: c.plan, sub_expires: c.expires, expired_notified: true, reminder_3d_sent: true, reminder_1d_sent: true };
      const ok = access.grantAccess(user, c.days, { now: NOW });
      const got = { ok, sub_expires: user.sub_expires, sub_status: user.sub_status, flags: [user.expired_notified, user.reminder_3d_sent, user.reminder_1d_sent] };
      const exp = { ok: c.ok, sub_expires: c.sub_expires, sub_status: c.sub_status, flags: c.flags };
      if (JSON.stringify(got) !== JSON.stringify(exp)) bad.push({ case: c, got });
    }
    expect(bad).toEqual([]);
  });

  it(`check_access + _is_pro — ${V.check_access.length} cases`, () => {
    const bad = [];
    for (const c of V.check_access) {
      const admin = c.uid === 123;
      const user = { user_id: c.uid, sub_status: c.status, sub_plan: c.plan, sub_expires: c.expires, long_active: c.flags[0], short_active: c.flags[1], vol_long_active: c.vol, vol_short_active: false, strategy: c.vol ? 'VOLUME' : 'SMC' };
      const result = access.checkAccess(user, { admin, now: NOW });
      const after = { sub_status: user.sub_status, sub_plan: user.sub_plan, long_active: user.long_active, short_active: user.short_active, vol_long_active: user.vol_long_active, strategy: user.strategy };
      const isPro = access.isPro({ user_id: c.uid, sub_status: c.status, sub_plan: c.plan, sub_expires: c.expires, long_active: false, short_active: false }, { admin, now: NOW });
      const got = { result, after, is_pro: isPro };
      const exp = { result: c.result, after: c.after, is_pro: c.is_pro };
      if (JSON.stringify(got) !== JSON.stringify(exp)) bad.push({ case: c, got });
    }
    expect(bad).toEqual([]);
  });

  it('normalize_plan / parse_strategies', () => {
    for (const [k, v] of Object.entries(V.normalize_plan)) {
      const input = k === 'None' ? null : (k === '0' ? 0 : k);
      expect(pf.normalizePlan(input), k).toBe(v);
    }
    for (const [k, v] of Object.entries(V.parse_strategies)) {
      expect(pf.parseStrategies(k === 'None' ? null : k), k).toEqual(v);
    }
  });
});
