/**
 * challengeService — pure parts against the bot's own Python
 * (fixture challenge_vectors.json, generated by gen/gen_challenge_vectors.py:
 *   cd /home/user/MAIN_BOT/CHM_BREAKER_V4 && BOT_TOKEN_CHM=test:token ADMIN_IDS=123 \
 *     <venv>/bin/python backend/tests/challenge/gen/gen_challenge_vectors.py \
 *     backend/tests/challenge/fixtures/challenge_vectors.json
 *   rm -f /home/user/MAIN_BOT/CHM_BREAKER_V4/signal_registry.json)
 *
 *   validation  challenge.build(77, answers, now) → to_json() | ValueError/TypeError str(e)
 *   plan        challenge.plan(ch, stats30, now) + plan_text(ru/en), 36 answer sets × 5 profiles × 3 nows
 *   progress    challenge.progress(ch, rows, now) + progress_text(ru/en, short) + block_text
 *   discipline  challenge.discipline(ch, today_signals, today_r) + daily_loss_r
 *   json        Challenge.from_json(raw).to_json() byte-identical; derived properties; _challenge_dict
 *   notify      notify_once(ch, key) with the eviction above 60 flags
 *   texts       _usd, _bar, _day_start/_day_key/hour, _T, _L, _OPTIONS, _answers, _parse_num
 */
import { describe, it, expect, beforeEach } from 'vitest';
import fs from 'fs';
import path from 'path';
import { createRequire } from 'module';

const nodeRequire = createRequire(import.meta.url);
const C = nodeRequire('../../services/challengeService.js');

const V = JSON.parse(fs.readFileSync(path.join(process.cwd(), 'tests', 'challenge', 'fixtures', 'challenge_vectors.json'), 'utf8'));
const norm = (x) => JSON.parse(JSON.stringify(x));
// gen_challenge_vectors.BASE
const BASE = Object.freeze({
  deposit: 1000, goal_kind: 'pct', goal_value: 25, term: '1m', risk_pct: 1, leverage: 5, max_trades_day: 3,
  daily_loss_pct: 3, topup_monthly: 0, strategies: ['LEVELS'], mode: 'signals',
});

function memKv() {
  const m = new Map();
  return {
    map: m,
    get: (k) => (m.has(k) ? m.get(k) : null),
    set: (k, v) => { m.set(k, String(v)); },
    itemsWithPrefix: (p) => [...m.entries()].filter(([k]) => k.startsWith(p)),
  };
}
const quietLog = { info() {}, warn() {}, debug() {}, error() {} };

beforeEach(() => {
  C.resetDeps();
  C.configure({ log: quietLog });
});

function pyErr(fn) {
  try {
    return { ok: true, value: fn() };
  } catch (e) {
    return { ok: false, etype: e instanceof C.Challenge ? 'x' : e.constructor.name.replace(/^Py/, ''), msg: e.message };
  }
}

describe('build(): validation table vs challenge.build', () => {
  const { now, uid, cases } = V.validation;
  it(`reproduces ${cases.length} answer sets (every answer, every boundary, coercion errors)`, () => {
    const bad = [];
    for (const c of cases) {
      const r = pyErr(() => C.build(uid, c.answers, now).toJson());
      if (c.ok) {
        if (!r.ok || r.value !== c.json) bad.push({ answers: c.answers, want: c.json, got: r });
      } else if (r.ok || r.etype !== c.etype || r.msg !== c.msg) {
        bad.push({ answers: c.answers, want: [c.etype, c.msg], got: r });
      } else if (C.badText(r.msg, 'ru') !== c.bad_ru || C.badText(r.msg, 'en') !== c.bad_en) {
        bad.push({ answers: c.answers, text: [c.bad_ru, C.badText(r.msg, 'ru')] });
      }
    }
    expect(bad).toEqual([]);
  });

  it('the first bad field in the bot order wins; ranges are checked before rounding', () => {
    // python -c "import challenge as C; C.build(1, {'deposit': 5, 'goal_kind': 'x', 'leverage': 0})"  → ValueError('deposit')
    expect(() => C.build(1, { deposit: 5, goal_kind: 'x', leverage: 0 })).toThrow('deposit');
    // python -c "import challenge as C; print(C.build(1, {'deposit': 1000, 'goal_value': 25, 'risk_pct': 0.1001, 'leverage': 5, 'strategies': ['SMC']}, now=0).risk_pct)" → 0.1
    expect(C.build(1, { deposit: 1000, goal_value: 25, risk_pct: 0.1001, leverage: 5, strategies: ['SMC'] }, 0).risk_pct).toBe(0.1);
    // python -c "import challenge as C; C.build(1, {'deposit': 1000, 'goal_value': 25, 'risk_pct': 0.099, 'leverage': 5, 'strategies': ['SMC']})" → ValueError('risk_pct')
    expect(() => C.build(1, { deposit: 1000, goal_value: 25, risk_pct: 0.099, leverage: 5, strategies: ['SMC'] })).toThrow('risk_pct');
  });

  it('isValueOrTypeError tells the Mini App which exceptions become bad_request', () => {
    let e1; let e2;
    try { C.build(1, { deposit: 'abc' }); } catch (e) { e1 = e; }
    try { C.build(1, { deposit: 100, goal_value: 5, risk_pct: 1, leverage: 1, strategies: 7 }); } catch (e) { e2 = e; }
    expect(C.isValueOrTypeError(e1)).toBe(true);
    expect(C.isValueOrTypeError(e2)).toBe(true);
    expect(e2.message).toBe("'int' object is not iterable");
    expect(C.isValueOrTypeError(new Error('x'))).toBe(false);
  });
});

describe('plan(): numbers, verdict, warnings vs challenge.plan', () => {
  it(`reproduces ${V.plan.length} (answers × stats profile × now) cases incl. plan_text ru/en`, () => {
    const bad = [];
    for (const c of V.plan) {
      const ch = C.build(78, c.answers, c.started);
      if (ch.toJson() !== c.json) { bad.push({ json: [c.json, ch.toJson()] }); continue; }
      const pl = C.plan(ch, c.stats, c.now);
      if (JSON.stringify(norm(pl)) !== JSON.stringify(norm(c.plan))) bad.push({ answers: c.answers, stats: c.stats, want: c.plan, got: pl });
      else if (C.planText(ch, pl, 'ru') !== c.text_ru || C.planText(ch, pl, 'en') !== c.text_en) {
        bad.push({ answers: c.answers, ru: [c.text_ru, C.planText(ch, pl, 'ru')], en: [c.text_en, C.planText(ch, pl, 'en')] });
      }
    }
    expect(bad).toEqual([]);
  });

  it('covers every verdict and every warning', () => {
    const verdicts = new Set(V.plan.map((c) => c.plan.verdict));
    const warns = new Set(V.plan.flatMap((c) => c.plan.warnings));
    expect([...verdicts].sort()).toEqual(['negative', 'no_data', 'ok', 'tight', 'unrealistic']);
    expect([...warns].sort()).toEqual(['daily_limit_below_risk', 'liquidation_near', 'margin_over_deposit', 'risk_high']);
  });

  it('r_per_day_needed is None without a deadline and stats None counts as no data', () => {
    // python -c "import challenge as C; ch=C.build(1, {'deposit':1000,'goal_value':25,'risk_pct':1,'leverage':5,'strategies':['LEVELS']}, now=0); print(C.plan(ch, None, now=0))"
    const ch = C.build(1, { deposit: 1000, goal_value: 25, risk_pct: 1, leverage: 5, strategies: ['LEVELS'] }, 0);
    expect(C.plan(ch, null, 0)).toEqual({
      goal_usd: 1250, profit_usd: 250, risk_usd: 10, r_needed: 25, days_total: 0, days_left: null,
      hist_trades: 0, hist_rr: 0, hist_r_per_day: 0, r_per_day_needed: null, days_forecast: null,
      verdict: 'no_data', warnings: [], margin_pct: 13.3,
    });
  });
});

describe('progress(): accounting vs challenge.progress (db/signal_outcome rules)', () => {
  it(`reproduces ${V.progress.length} seeded challenges incl. texts`, () => {
    const bad = [];
    for (const c of V.progress) {
      const ch = C.fromJson(c.json);
      expect(ch.toJson()).toBe(c.json);
      const pr = C.progress(ch, c.rows, c.now);
      if (JSON.stringify(norm(pr)) !== JSON.stringify(norm(c.progress))) { bad.push({ json: c.json, want: c.progress, got: pr }); continue; }
      const t = {
        ru: C.progressText(ch, pr, 'ru'), en: C.progressText(ch, pr, 'en'),
        ru_short: C.progressText(ch, pr, 'ru', true), en_short: C.progressText(ch, pr, 'en', true),
        block_ru: pr.blocked ? C.blockText(pr.block_reason, 'ru') : null,
        block_en: pr.blocked ? C.blockText(pr.block_reason, 'en') : null,
      };
      for (const k of Object.keys(t)) if (t[k] !== c[k]) bad.push({ k, want: c[k], got: t[k] });
    }
    expect(bad).toEqual([]);
  });

  it('covers goal_reached, both block reasons, negative R and top-ups', () => {
    const P = V.progress.map((c) => c.progress);
    expect(P.some((p) => p.goal_reached)).toBe(true);
    expect(P.some((p) => p.block_reason === 'max_trades')).toBe(true);
    expect(P.some((p) => p.block_reason === 'daily_loss')).toBe(true);
    expect(P.some((p) => p.r_total < 0)).toBe(true);
    expect(P.some((p) => p.topups_total > 0)).toBe(true);
    expect(P.some((p) => p.pace_r !== null && p.pace_r < 0)).toBe(true);
  });
});

describe('discipline()', () => {
  it(`reproduces the ${V.discipline.length}-row table (status × limits × today)`, () => {
    const bad = [];
    for (const [status, mtd, risk, dlp, sig, tr, b, reason, lim] of V.discipline) {
      const ch = new C.Challenge({
        user_id: 1, started_at: V.t0, deposit: 1000.0, goal_kind: 'pct', goal_value: 10.0,
        risk_pct: risk, max_trades_day: mtd, daily_loss_pct: dlp, status,
      });
      const got = C.discipline(ch, sig, tr);
      if (got[0] !== b || got[1] !== reason || ch.daily_loss_r !== lim) bad.push({ status, mtd, risk, dlp, sig, tr, want: [b, reason, lim], got: [...got, ch.daily_loss_r] });
    }
    expect(bad).toEqual([]);
  });
});

describe('kv JSON: from_json / to_json byte-identical', () => {
  it('from_json drops unknown keys, keeps the dataclass order, refuses non-dicts', () => {
    const bad = [];
    for (const c of V.from_json) {
      const r = pyErr(() => { const ch = C.fromJson(c.raw); return ch === null ? null : ch.toJson(); });
      if (c.ok ? (!r.ok || r.value !== c.json) : (r.ok || r.etype !== c.etype || r.msg !== c.msg)) bad.push({ raw: c.raw, want: c, got: r });
    }
    expect(bad).toEqual([]);
  });

  it('derived properties and the Mini App dict', () => {
    for (const c of V.derived) {
      const ch = C.fromJson(c.json);
      for (const k of ['goal_usd', 'goal_profit_usd', 'risk_usd', 'r_needed', 'topups_total', 'daily_loss_r']) expect(ch[k]).toBe(c[k]);
      expect(norm(C.challengeDict(ch))).toEqual(norm(c.dict));
      expect(Object.keys(C.challengeDict(ch))).toEqual(Object.keys(c.dict));
    }
  });

  it('notify_once: flags, repeats, eviction of the 30 oldest above 60 (stamps = the wall clock)', () => {
    const kv = memKv();
    let clock = 0;
    C.configure({ kv, clock: () => clock });
    const ch = C.build(82, BASE, V.t0);
    expect(ch.toJson()).toBe(V.notify_once.start_json);
    for (const s of V.notify_once.steps) {
      clock = s.clock;
      const r = C.notifyOnce(ch, s.key);
      expect([s.key, r, Object.keys(ch.notified).length]).toEqual([s.key, s.ret, s.n]);
      expect(kv.get('challenge_82')).toBe(s.json);
    }
  });

  it('add_topup / finish: validation, rounding, JSON', () => {
    const kv = memKv();
    C.configure({ kv });
    const ch = C.fromJson(V.topup.start_json);
    for (const s of V.topup.steps) {
      const r = pyErr(() => { C.addTopup(ch, s.amount, V.t0 + 50.75); return ch.toJson(); });
      if (s.ok) {
        expect(r).toEqual({ ok: true, value: s.json });
        expect(ch.topups_total).toBe(s.total);
        expect(kv.get('challenge_83')).toBe(s.json);
      } else {
        expect([r.ok, r.etype, r.msg]).toEqual([false, s.etype, s.msg]);
      }
    }
    C.finish(ch, C.STATUS_CANCELLED, V.t0 + 999.5);
    expect(ch.toJson()).toBe(V.topup.finished_json);
    expect(kv.get('challenge_83')).toBe(V.topup.finished_json);
  });
});

describe('texts and helpers', () => {
  it('_usd / _bar / _day_start / _day_key / hour', () => {
    for (const [v, s] of V.usd) expect([v, C.usd(v)]).toEqual([v, s]);
    for (const [v, s] of V.bar) expect([v, C.bar(v)]).toEqual([v, s]);
    for (const [t, d0, key, hour] of V.days) expect([t, C.dayStart(t), C.dayKey(t), C.utcHour(t)]).toEqual([t, d0, key, hour]);
    // python -c "print(repr(-0.0))" → the fixture keeps 0 for -0.0: check the sign branch explicitly
    expect(C.usd(-0.0)).toBe('$-0');
  });

  it('block_text for every reason and language (non-en → ru)', () => {
    for (const [r, by] of Object.entries(V.block)) for (const [lg, s] of Object.entries(by)) expect(C.blockText(r, lg)).toBe(s);
  });

  it('the bot dictionaries verbatim (_T, _L, _OPTIONS, STEPS)', () => {
    expect(norm(C.T)).toEqual(V.core_texts);
    expect(norm(C.L)).toEqual(V.handler_texts);
    expect(norm(C.OPTIONS)).toEqual(V.handler_options);
    expect(C.STEPS).toEqual(V.steps);
    expect(C.CUSTOM_STEPS).toEqual(V.custom_steps);
  });

  it('_parse_num and _answers (questionnaire state → answers)', () => {
    for (const [s, n] of V.parse_num) expect([s, C.parseNum(s)]).toEqual([s, n]);
    for (const c of V.answers_from_state) {
      const r = pyErr(() => C.answersFromState(c.state));
      if (c.ok) expect(norm(r.value)).toEqual(c.answers);
      else expect([r.etype, r.msg]).toEqual([c.etype, c.msg]);
    }
  });

  it('cb_go text: started + applied + skipped (auto_trade → no keys)', () => {
    for (const c of V.started_text) expect(C.startedText(c.res, c.lang)).toBe(c.text);
    // python -c "print('Пополнение учтено: ' + f'${2500.5:,.0f}'.replace(',', ' '))" → Пополнение учтено: $2 500
    expect(C.topupOkText(2500.5, 'ru')).toBe('Пополнение учтено: $2 500');
    expect(C.topupOkText(12345, 'en')).toBe('Top-up recorded: $12 345');
  });

  it('env config: LOOP_INTERVAL_S ≥ 60, DAILY_HOUR_UTC clamped to 0..23', () => {
    expect(C.CONFIG).toEqual({ LOOP_INTERVAL_S: V.loop_interval_s, DAILY_HOUR_UTC: V.daily_hour_utc });
    // python: max(60.0, float('5' or 600)) → 60.0; max(0, min(23, int('99' or 20))) → 23
    expect(C.readConfig({ CHALLENGE_LOOP_INTERVAL_S: '5', CHALLENGE_DAILY_HOUR_UTC: '99' })).toEqual({ LOOP_INTERVAL_S: 60, DAILY_HOUR_UTC: 23 });
    expect(C.readConfig({ CHALLENGE_LOOP_INTERVAL_S: '', CHALLENGE_DAILY_HOUR_UTC: '-4' })).toEqual({ LOOP_INTERVAL_S: 600, DAILY_HOUR_UTC: 0 });
    expect(() => C.readConfig({ CHALLENGE_DAILY_HOUR_UTC: '7.5' })).toThrow("invalid literal for int() with base 10: '7.5'");
  });
});

describe('aggregate / signal_status (local port of db/signal_outcome, db/signal_stats)', () => {
  it('the TP1/TP2 double count, MISSED / EXPIRED / ghost SKIP rules hold', () => {
    const now = V.t0;
    const base = { entry: 100, sl: 98, original_sl: 98, tp1: 102, tp2: 104, tp3: 105, signal_msg_id: 5, order_id: '' };
    const rows = [
      { ...base, progress_stage: 'TP1', created_at: now - 100, strategy: 'SMC' },
      { ...base, progress_stage: 'MISSED', created_at: now - 90, strategy: 'LEVELS' },
      { ...base, progress_stage: 'EXPIRED', expire_rr: 0.555, created_at: now - 80, strategy: 'VOLUME' },
      { ...base, result: 'SKIP', signal_msg_id: 0, created_at: now - 70 },
      { ...base, result: 'SL', result_rr: -1, order_id: 'x', created_at: now - 60, strategy: 'smc' },
    ];
    // python -c "from db.signal_stats import aggregate; ..." (same rows) → signals 5, open 1, missed 1, expired 1,
    // trades 3 (TP1 1.0, EXPIRED 0.56 (round(0.555, 2) = 0.56 on the exact binary), SL -1.0), total_rr 0.56
    const a = C.aggregate(rows, 30, now);
    expect([a.signals, a.open, a.missed, a.expired, a.trades, a.total_rr, a.wins, a.losses]).toEqual([5, 1, 1, 1, 3, 0.56, 2, 1]);
    expect(a.per_strategy.SMC.trades).toBe(2);
  });
});
